// The high-value language lane: small words and complete chunks that let a
// beginner coordinate real life before the folklore vocabulary widens out.
// These are synthetic teaching examples, not copied private conversations.

export const EVERYDAY_CORE_SENSE_IDS = Object.freeze([
  // people, identity and the verbs that carry most conversation
  'ti', 'ju', 'une', 'ne_we', 'ai', 'ajo', 'ata',
  'jam', 'je', 'eshte', 'ka', 'ke', 'bej', 'vjen', 'shko', 'rri', 'prit',
  'nisem', 'takohem', 'mbaroj', 'di', 'mund', 'duhet', 'do_fut', 'dot',

  // yes/no, questions and conversational glue
  'po_yes', 'po_prog', 'po_turn', 'jo', 'nuk', 'a_q',
  'kush', 'cfare', 'ku', 'kur', 'pse', 'si', 'sa',
  'dhe', 'edhe', 'apo', 'se', 'nese', 'per', 'me', 'ne', 'tek', 'nga',
  'shume', 'pak', 'mire', 'keq', 'rregull', 'nejse',

  // time, place and ordinary needs
  'tani', 'sot', 'sonte', 'neser', 'dje', 'mengjes', 'mbremje', 'vone', 'akoma',
  'ketu', 'atje', 'shtepi', 'pune', 'njeri', 'mik', 'familje', 'motra', 'vella', 'nje',
  'uje', 'ushqim', 'buke', 'kafe',

  // the turns that make a conversation continue instead of becoming a phrase list
  'quhem', 'jeto', 'punon', 'yt', 'im', 'prane',
  'mendoj', 'dakord', 'drejte', 'lajm', 'tregoj', 'vertet', 'pastaj', 'problem',
  'lodhur', 'etur', 'frike', 'mungon', 'shi', 'bie', 'ftohte', 'kujdes', 'harron', 'sjell',
  'qesh', 'shaka',

  // social softeners and repair
  'pershendetje', 'faleminderit', 'lutem', 'fal', 'mirupafshim', 'mireseerdhe',
  'gezuar', 'ditelindje', 'gjitheve', 'njeqind', 'skuqem',

  // concrete can-do actions: repair, directions, food and simple transactions
  'ha', 'pi', 'ndihmo', 'kuptoj', 'perserit', 'ngadale', 'pelqen', 'nevoje', 'dhemb',
  'majtas', 'djathtas', 'drejt', 'afer', 'treg', 'dyqan', 'blej', 'kushton',
  'lek', 'kripe', 'oda', 'bujtine', 'dhome', 'shtrat', 'fle', 'naten',
  'mjek', 'sherues', 'semur', 'dhimbje', 'shok',
])

export const EVERYDAY_CORE_SENSE_SET = new Set(EVERYDAY_CORE_SENSE_IDS)

// Release targets for the opening conversation. Keeping these in public code
// makes the learning promise testable without putting research transcripts in
// the repository.
export const FIRST_MINUTES_PHRASES = Object.freeze([
  { al: 'përshëndetje!', maxDepth: 1, interactive: true },
  { al: 'si je?', maxDepth: 1 },
  { al: 'jam mirë, faleminderit. po ti?', maxDepth: 1, interactive: true },
  { al: 'ku po shkon?', maxDepth: 2 },
  { al: 'po shkoj në fshat.', maxDepth: 2, interactive: true },
  { al: 'po nisem tani. a vjen?', maxDepth: 3 },
  { al: 'po, po vij.', maxDepth: 3, interactive: true },
  { al: 'më fal, nuk vij dot.', maxDepth: 3, interactive: true },
  { al: 's\'ka gjë. shihemi nesër.', maxDepth: 4 },
  { al: 'prit pak, të lutem.', maxDepth: 4 },
  { al: 'nuk e di.', maxDepth: 4 },
  { al: 'ku do të takohemi?', maxDepth: 4 },
  { al: 'takohemi në shesh.', maxDepth: 4, interactive: true },
  { al: 'takohemi te kroi.', maxDepth: 4, interactive: true },
  { al: 'sot apo nesër?', maxDepth: 5 },
  { al: 'në çfarë ore?', maxDepth: 5 },
  { al: 'sot, tani.', maxDepth: 5, interactive: true },
  { al: 'nesër në mëngjes.', maxDepth: 5, interactive: true },
  { al: 'mirupafshim!', maxDepth: 4, interactive: true },
])

// A learner who keeps walking into the village should meet these additional
// coordination and need phrases in the same first play session. They are
// intentionally ordinary enough to transfer directly to speech or messaging.
export const FIRST_SESSION_PHRASES = Object.freeze([
  { al: 'ku je?', maxDepth: 3 },
  { al: 'jam në punë.', maxDepth: 3 },
  { al: 'kur mbaron?', maxDepth: 3 },
  { al: 'sa të mbaroj punën, do të nisem.', maxDepth: 3 },
  { al: 'në rregull. shihemi më vonë.', maxDepth: 3 },
  { al: 'çfarë do?', maxDepth: 2 },
  { al: 'dua ujë, të lutem.', maxDepth: 2 },
  { al: 'sot është ditëlindja ime.', maxDepth: 2 },
  { al: 'gëzuar ditëlindjen!', maxDepth: 2 },
  { al: 'edhe njëqind!', maxDepth: 2 },
  { al: 'faleminderit të gjithëve!', maxDepth: 2 },
  { al: 'tani po skuqem!', maxDepth: 2 },
  { al: 'nejse, dua çaj.', maxDepth: 2 },
  { al: 'a mund të më ndihmosh?', maxDepth: 6 },
  { al: 'kush do të vijë?', maxDepth: 6 },
  { al: 'a ka njeri këtu?', maxDepth: 7 },
  { al: 'ku është tregu?', maxDepth: 7 },
  { al: 'majtas apo djathtas?', maxDepth: 7 },
  { al: 'drejt, pastaj djathtas.', maxDepth: 7 },
  { al: 'nuk kuptoj.', maxDepth: 8 },
  { al: 'fol ngadalë, të lutem.', maxDepth: 8 },
  { al: 'dua bukë dhe kripë, ju lutem.', maxDepth: 9 },
  { al: 'jam rrugës.', maxDepth: 10 },
  { al: 'a ke ngrënë?', maxDepth: 10 },
  { al: 'të bëftë mirë!', maxDepth: 11 },
  { al: 'sill bukë dhe kripë, të lutem.', maxDepth: 3 },
  { al: 'mos harro kripën.', maxDepth: 3 },
  { al: 'më jep bukën, të lutem.', maxDepth: 7 },
  { al: 'po, merre.', maxDepth: 7 },
  { al: 'si quhesh?', maxDepth: 7 },
  { al: 'nga je?', maxDepth: 7 },
  { al: 'ku jeton?', maxDepth: 7 },
  { al: 'çfarë pune bën?', maxDepth: 7 },
  { al: 'jam nga Gjakovë.', maxDepth: 7 },
  { al: 'jetoj pranë tregut.', maxDepth: 7 },
  { al: 'punoj në treg.', maxDepth: 7 },
  { al: 'si është familja jote?', maxDepth: 7 },
  { al: 'familja ime është mirë.', maxDepth: 7 },
  { al: 'kam një motër dhe një vëlla.', maxDepth: 7 },
  { al: 'si shkoi rruga?', maxDepth: 7 },
  { al: 'dje binte shi.', maxDepth: 7 },
  { al: 'tani jam i lodhur, por jam mirë.', maxDepth: 7 },
  { al: 'kam një lajm. ka një problem.', maxDepth: 7 },
  { al: 'vërtet? pastaj?', maxDepth: 7 },
  { al: 'më trego çfarë ndodhi.', maxDepth: 7 },
  { al: 'e kuptoj, por kam frikë.', maxDepth: 7 },
  { al: 'çfarë mendon?', maxDepth: 7 },
  { al: 'nuk jam dakord.', maxDepth: 7 },
  { al: 'mendoj se ke të drejtë.', maxDepth: 7, interactive: true },
  { al: 'a mund të hyj?', maxDepth: 6 },
  { al: 'a do ujë?', maxDepth: 6 },
  { al: 'jam i etur.', maxDepth: 6 },
  { al: 'po, faleminderit.', maxDepth: 6 },
  { al: 'nuk më pëlqen kafeja.', maxDepth: 7 },
  { al: 'më mungon familja ime.', maxDepth: 7 },
  { al: 'më vjen keq.', maxDepth: 7 },
  { al: 'a je mirë?', maxDepth: 7 },
  { al: 'ki kujdes!', maxDepth: 7 },
  { al: 'unë vetëm po bëj shaka.', maxDepth: 2 },
  { al: 'a ke fjetur?', maxDepth: 4 },
])

// Whole-chunk practice is the speed lane. Each prompt reinforces every sense
// needed to understand or speak the phrase, instead of making the learner win
// five unrelated single-word questions before using one ordinary response.
export const EVERYDAY_PHRASE_DRILLS = Object.freeze([
  { id: 'hello', al: 'përshëndetje!', en: 'Hello!', requires: ['pershendetje'] },
  { id: 'how-are-you', al: 'si je?', en: 'How are you?', requires: ['si', 'je'] },
  { id: 'well-thanks-you', al: 'jam mirë, faleminderit. po ti?', en: 'I am well, thank you. And you?', requires: ['jam', 'mire', 'faleminderit', 'po_turn', 'ti'] },
  { id: 'where-going', al: 'ku po shkon?', en: 'Where are you going?', requires: ['ku', 'po_prog', 'shko'] },
  { id: 'going-village', al: 'po shkoj në fshat.', en: 'I am going to the village.', requires: ['po_prog', 'shko', 'ne', 'fshat'] },
  { id: 'setting-off-coming', al: 'po nisem tani. a vjen?', en: 'I am setting off now. Are you coming?', requires: ['po_prog', 'nisem', 'tani', 'a_q', 'vjen'] },
  { id: 'yes-coming', al: 'po, po vij.', en: 'Yes, I am coming.', requires: ['po_yes', 'po_prog', 'vjen'] },
  { id: 'cannot-come', al: 'më fal, nuk vij dot.', en: 'Sorry, I cannot come.', requires: ['me_obj', 'fal', 'nuk', 'vjen', 'dot'] },
  { id: 'no-problem-tomorrow', al: "s'ka gjë. shihemi nesër.", en: 'No problem. See you tomorrow.', requires: ['ka', 'gje', 'sheh', 'neser'] },
  { id: 'wait-please', al: 'prit pak, të lutem.', en: 'Wait a moment, please.', requires: ['prit', 'pak', 'lutem'] },
  { id: 'dont-know', al: 'nuk e di.', en: "I don't know.", requires: ['nuk', 'e_obj', 'di'] },
  { id: 'where-meet', al: 'ku do të takohemi?', en: 'Where will we meet?', requires: ['ku', 'do_fut', 'te_subj', 'takohem'] },
  { id: 'meet-square', al: 'takohemi në shesh.', en: 'We will meet in the square.', requires: ['takohem', 'ne', 'shesh'] },
  { id: 'meet-spring', al: 'takohemi te kroi.', en: 'We will meet at the spring.', requires: ['takohem', 'tek', 'krua'] },
  { id: 'today-tomorrow', al: 'sot apo nesër?', en: 'Today or tomorrow?', requires: ['sot', 'apo', 'neser'] },
  { id: 'what-time', al: 'në çfarë ore?', en: 'At what time?', requires: ['ne', 'cfare', 'ore'] },
  { id: 'today-now', al: 'sot, tani.', en: 'Today, now.', requires: ['sot', 'tani'] },
  { id: 'tomorrow-morning', al: 'nesër në mëngjes.', en: 'Tomorrow morning.', requires: ['neser', 'ne', 'mengjes'] },
  { id: 'where-are-you', al: 'ku je?', en: 'Where are you?', requires: ['ku', 'je'] },
  { id: 'at-work', al: 'jam në punë.', en: 'I am at work.', requires: ['jam', 'ne', 'pune'] },
  { id: 'when-finish', al: 'kur mbaron?', en: 'When do you finish?', requires: ['kur', 'mbaroj'] },
  { id: 'finish-set-off', al: 'sa të mbaroj punën, do të nisem.', en: 'As soon as I finish work, I will set off.', requires: ['sa', 'te_subj', 'mbaroj', 'pune', 'do_fut', 'nisem'] },
  { id: 'all-right-later', al: 'në rregull. shihemi më vonë.', en: 'All right. See you later.', requires: ['ne', 'rregull', 'sheh', 'me_more', 'vone'] },
  { id: 'what-want', al: 'çfarë do?', en: 'What do you want?', requires: ['cfare', 'do'] },
  { id: 'want-water', al: 'dua ujë, të lutem.', en: 'I want water, please.', requires: ['do', 'uje', 'lutem'] },
  { id: 'my-birthday', al: 'sot është ditëlindja ime.', en: 'Today is my birthday.', requires: ['sot', 'eshte', 'ditelindje', 'im'] },
  { id: 'happy-birthday', al: 'gëzuar ditëlindjen!', en: 'Happy birthday!', requires: ['gezuar', 'ditelindje'] },
  { id: 'many-returns', al: 'edhe njëqind!', en: 'Many happy returns!', requires: ['edhe', 'njeqind'] },
  { id: 'thanks-everyone', al: 'faleminderit të gjithëve!', en: 'Thank you, everyone!', requires: ['faleminderit', 'gjitheve'] },
  { id: 'blushing-now', al: 'tani po skuqem!', en: 'Now I am blushing!', requires: ['tani', 'po_prog', 'skuqem'] },
  { id: 'anyway-want-tea', al: 'nejse, dua çaj.', en: 'Anyway, I would like tea.', requires: ['nejse', 'do', 'caj'] },
  { id: 'bring-bread-salt', al: 'sill bukë dhe kripë, të lutem.', en: 'Bring bread and salt, please.', requires: ['sjell', 'buke', 'dhe', 'kripe', 'lutem'] },
  { id: 'dont-forget-salt', al: 'mos harro kripën.', en: 'Do not forget the salt.', requires: ['mos', 'harron', 'kripe'] },
  { id: 'give-bread', al: 'më jep bukën, të lutem.', en: 'Give me the bread, please.', requires: ['me_obj', 'jep', 'buke', 'lutem'] },
  { id: 'yes-take-it', al: 'po, merre.', en: 'Yes, take it.', requires: ['po_yes', 'merr'] },
  { id: 'your-name', al: 'si quhesh?', en: 'What is your name?', requires: ['si', 'quhem'] },
  { id: 'where-from', al: 'nga je?', en: 'Where are you from?', requires: ['nga', 'je'] },
  { id: 'where-live', al: 'ku jeton?', en: 'Where do you live?', requires: ['ku', 'jeto'] },
  { id: 'what-work', al: 'çfarë pune bën?', en: 'What work do you do?', requires: ['cfare', 'pune', 'bej'] },
  { id: 'from-gjakova', al: 'jam nga Gjakovë.', en: 'I am from Gjakova.', requires: ['jam', 'nga', 'gjakove'] },
  { id: 'live-near-market', al: 'jetoj pranë tregut.', en: 'I live near the market.', requires: ['jeto', 'prane', 'treg'] },
  { id: 'work-market', al: 'punoj në treg.', en: 'I work in the market.', requires: ['punon', 'ne', 'treg'] },
  { id: 'how-family', al: 'si është familja jote?', en: 'How is your family?', requires: ['si', 'eshte', 'familje', 'yt'] },
  { id: 'family-well', al: 'familja ime është mirë.', en: 'My family is well.', requires: ['familje', 'im', 'eshte', 'mire'] },
  { id: 'have-siblings', al: 'kam një motër dhe një vëlla.', en: 'I have one sister and one brother.', requires: ['ka', 'nje', 'motra', 'dhe', 'vella'] },
  { id: 'how-road-went', al: 'si shkoi rruga?', en: 'How did the journey go?', requires: ['si', 'shko', 'rruge'] },
  { id: 'rained-yesterday', al: 'dje binte shi.', en: 'It was raining yesterday.', requires: ['dje', 'bie', 'shi'] },
  { id: 'it-was-cold', al: 'ishte ftohtë.', en: 'It was cold.', requires: ['eshte', 'ftohte'] },
  { id: 'tired-but-well', al: 'tani jam i lodhur, por jam mirë.', en: 'Now I am tired, but I am well.', requires: ['tani', 'jam', 'i_art', 'lodhur', 'por', 'mire'] },
  { id: 'news-problem', al: 'kam një lajm. ka një problem.', en: 'I have news. There is a problem.', requires: ['ka', 'nje', 'lajm', 'problem'] },
  { id: 'really-then', al: 'vërtet? pastaj?', en: 'Really? Then what?', requires: ['vertet', 'pastaj'] },
  { id: 'tell-what-happened', al: 'më trego çfarë ndodhi.', en: 'Tell me what happened.', requires: ['me_obj', 'tregoj', 'cfare', 'ndodh'] },
  { id: 'understand-afraid', al: 'e kuptoj, por kam frikë.', en: 'I understand, but I am afraid.', requires: ['e_obj', 'kuptoj', 'por', 'ka', 'frike'] },
  { id: 'dont-believe-it', al: 'nuk e besoj.', en: 'I do not believe it.', requires: ['nuk', 'e_obj', 'beso'] },
  { id: 'what-think', al: 'çfarë mendon?', en: 'What do you think?', requires: ['cfare', 'mendoj'] },
  { id: 'dont-agree', al: 'nuk jam dakord.', en: 'I do not agree.', requires: ['nuk', 'jam', 'dakord'] },
  { id: 'think-you-right', al: 'mendoj se ke të drejtë.', en: 'I think you are right.', requires: ['mendoj', 'se', 'ke', 'te_link', 'drejte'] },
  { id: 'may-enter', al: 'a mund të hyj?', en: 'May I come in?', requires: ['a_q', 'mund', 'te_subj', 'hyr'] },
  { id: 'want-water-question', al: 'a do ujë?', en: 'Do you want water?', requires: ['a_q', 'do', 'uje'] },
  { id: 'am-thirsty', al: 'jam i etur.', en: 'I am thirsty.', requires: ['jam', 'i_art', 'etur'] },
  { id: 'yes-thank-you', al: 'po, faleminderit.', en: 'Yes, thank you.', requires: ['po_yes', 'faleminderit'] },
  { id: 'miss-family', al: 'më mungon familja ime.', en: 'I miss my family.', requires: ['me_obj', 'mungon', 'familje', 'im'] },
  { id: 'sorry-sympathy', al: 'më vjen keq.', en: 'I am sorry.', requires: ['me_obj', 'vjen', 'keq'] },
  { id: 'are-you-well', al: 'a je mirë?', en: 'Are you all right?', requires: ['a_q', 'je', 'mire'] },
  { id: 'be-careful', al: 'ki kujdes!', en: 'Be careful!', requires: ['ke', 'kujdes'] },
  { id: 'only-joking', al: 'unë vetëm po bëj shaka.', en: 'I am only joking.', requires: ['une', 'vetem', 'po_prog', 'bej', 'shaka'] },
  { id: 'have-slept', al: 'a ke fjetur?', en: 'Have you slept?', requires: ['a_q', 'ke', 'fle'] },
  { id: 'can-help-me', al: 'a mund të më ndihmosh?', en: 'Can you help me?', requires: ['a_q', 'mund', 'te_subj', 'me_obj', 'ndihmo'] },
  { id: 'yes-help-you', al: 'po, mund të të ndihmoj.', en: 'Yes, I can help you.', requires: ['po_yes', 'mund', 'te_subj', 'te_obj', 'ndihmo'] },
  { id: 'who-will-come', al: 'kush do të vijë?', en: 'Who will come?', requires: ['kush', 'do_fut', 'te_subj', 'vjen'] },
  { id: 'anyone-here', al: 'a ka njeri këtu?', en: 'Is anyone here?', requires: ['a_q', 'ka', 'njeri', 'ketu'] },
  { id: 'where-market', al: 'ku është tregu?', en: 'Where is the market?', requires: ['ku', 'eshte', 'treg'] },
  { id: 'where-guest-room', al: 'ku është oda?', en: 'Where is the guest-room?', requires: ['ku', 'eshte', 'oda'] },
  { id: 'left-or-right', al: 'majtas apo djathtas?', en: 'Left or right?', requires: ['majtas', 'apo', 'djathtas'] },
  { id: 'straight-then-right', al: 'drejt, pastaj djathtas.', en: 'Straight ahead, then right.', requires: ['drejt', 'pastaj', 'djathtas'] },
  { id: 'have-bread', al: 'keni bukë?', en: 'Do you have bread?', requires: ['ka', 'buke'] },
  { id: 'dont-understand', al: 'nuk kuptoj.', en: "I don't understand.", requires: ['nuk', 'kuptoj'] },
  { id: 'speak-slowly', al: 'fol ngadalë, të lutem.', en: 'Speak slowly, please.', requires: ['fol', 'ngadale', 'lutem'] },
  { id: 'repeat-please', al: 'përsërit, të lutem.', en: 'Repeat that, please.', requires: ['perserit', 'lutem'] },
  { id: 'what-does-it-mean', al: 'çfarë do të thotë?', en: 'What does it mean?', requires: ['cfare', 'do_fut', 'te_subj', 'thote'] },
  { id: 'bread-salt-please', al: 'dua bukë dhe kripë, ju lutem.', en: 'I would like bread and salt, please.', requires: ['do', 'buke', 'dhe', 'kripe', 'ju', 'lutem'] },
  { id: 'how-much-together', al: 'sa kushtojnë?', en: 'How much are they?', requires: ['sa', 'kushton'] },
  { id: 'on-my-way', al: 'jam rrugës.', en: 'I am on my way.', requires: ['jam', 'rruge'] },
  { id: 'what-doing', al: 'çfarë po bën?', en: 'What are you doing?', requires: ['cfare', 'po_prog', 'bej'] },
  { id: 'have-eaten', al: 'a ke ngrënë?', en: 'Have you eaten?', requires: ['a_q', 'ke', 'ha'] },
  { id: 'am-hungry', al: 'jo, jam i uritur.', en: 'No, I am hungry.', requires: ['jo', 'jam', 'i_art', 'uritur'] },
  { id: 'come-eat-with-us', al: 'hajde. ha bukë me ne.', en: 'Come. Eat bread with us.', requires: ['hajde', 'ha', 'buke', 'me', 'ne_we'] },
  { id: 'bon-appetit', al: 'të bëftë mirë!', en: 'Enjoy your meal!', requires: ['te_obj', 'bej', 'mire'] },
  { id: 'like-tea', al: 'më pëlqen çaji.', en: 'I like the tea.', requires: ['me_obj', 'pelqen', 'caj'] },
  { id: 'dont-like-coffee', al: 'nuk më pëlqen kafeja.', en: "I don't like coffee.", requires: ['nuk', 'me_obj', 'pelqen', 'kafe'] },
  { id: 'need-doctor', al: 'kam nevojë për një mjek.', en: 'I need a doctor.', requires: ['ka', 'nevoje', 'per', 'nje', 'mjek'] },
  { id: 'hurts-here', al: 'më dhemb këtu.', en: 'It hurts here.', requires: ['me_obj', 'dhemb', 'ketu'] },
  { id: 'need-help', al: 'kam nevojë për ndihmë.', en: 'I need help.', requires: ['ka', 'nevoje', 'per', 'ndihmo'] },
  { id: 'need-room-tonight', al: 'kam nevojë për një dhomë sonte.', en: 'I need a room tonight.', requires: ['ka', 'nevoje', 'per', 'nje', 'dhome', 'sonte'] },
  { id: 'night-price', al: 'sa kushton një natë?', en: 'How much does one night cost?', requires: ['sa', 'kushton', 'nje', 'naten'] },
  { id: 'sleep-here', al: 'a mund të fle këtu?', en: 'Can I sleep here?', requires: ['a_q', 'mund', 'te_subj', 'fle', 'ketu'] },
  { id: 'coffee-please', al: 'dua kafe, të lutem.', en: 'I would like coffee, please.', requires: ['do', 'kafe', 'lutem'] },
  // Daily rhythm and return visits recur naturally at inns, stalls, roads and
  // guest-rooms. Keeping them in the phrase lane turns ambient world life into
  // language the player can actually reuse outside the tale.
  { id: 'good-morning', al: 'mirëmëngjes!', en: 'Good morning!', requires: ['mirmengjes'] },
  { id: 'good-evening', al: 'mirëmbrëma!', en: 'Good evening!', requires: ['mirembrema'] },
  { id: 'sleep-good-night', al: 'fle mirë! natën e mirë!', en: 'Sleep well! Good night!', requires: ['fle', 'mire', 'naten', 'e_art'] },
  { id: 'thanks-come-again', al: 'faleminderit! të lutem, eja përsëri!', en: 'Thank you! Please come again!', requires: ['faleminderit', 'lutem', 'vjen', 'perseri'] },
  { id: 'thanks-goodbye', al: 'faleminderit dhe mirupafshim!', en: 'Thank you and goodbye!', requires: ['faleminderit', 'dhe', 'mirupafshim'] },
  { id: 'welcome-enter', al: 'po, hyr. mirë se erdhe!', en: 'Yes, come in. Welcome!', requires: ['po_yes', 'hyr', 'mire', 'se', 'vjen'] },
  { id: 'were-you-away', al: 'ti ishe larg?', en: 'Were you away?', requires: ['ti', 'eshte', 'larg'] },
  { id: 'still-not-slept', al: 'jo, akoma nuk kam fjetur.', en: 'No, I still have not slept.', requires: ['jo', 'akoma', 'nuk', 'ka', 'fle'] },
  { id: 'happy-going-home', al: 'unë jam i lumtur: unë shkoj në shtëpi.', en: 'I am happy: I am going home.', requires: ['une', 'jam', 'i_art', 'lumtur', 'shko', 'ne', 'shtepi'] },
  { id: 'have-an-idea', al: 'unë kam një ide: është një mundësi.', en: 'I have an idea: there is a possibility.', requires: ['une', 'ka', 'nje', 'ide', 'eshte', 'mundesi'] },
  { id: 'when-rain-coming', al: 'kur vjen shiu?', en: 'When is the rain coming?', requires: ['kur', 'vjen', 'shi'] },
  { id: 'take-care-tonight', al: 'kujdes sonte!', en: 'Take care tonight!', requires: ['kujdes', 'sonte'] },
  { id: 'good-luck-tomorrow', al: 'fat i mirë nesër!', en: 'Good luck tomorrow!', requires: ['fat', 'i_art', 'mire', 'neser'] },
])

// The whole-phrase bank must not become a shapeless list. These groups state
// the practical outcomes it has to keep covering as story content grows.
export const EVERYDAY_CAN_DO_GROUPS = Object.freeze([
  { id: 'social', label: 'greet, respond and read social tone', minimum: 8, drillIds: ['hello', 'how-are-you', 'well-thanks-you', 'good-morning', 'good-evening', 'happy-birthday', 'thanks-everyone', 'blushing-now', 'anyway-want-tea', 'only-joking'] },
  { id: 'introduce', label: 'introduce yourself and learn about someone', minimum: 6, drillIds: ['your-name', 'where-from', 'where-live', 'what-work', 'from-gjakova', 'live-near-market', 'work-market'] },
  { id: 'family', label: 'ask about family and answer', minimum: 4, drillIds: ['how-family', 'family-well', 'have-siblings', 'miss-family'] },
  { id: 'coordinate', label: 'locate people and make plans', minimum: 8, drillIds: ['where-going', 'setting-off-coming', 'where-meet', 'today-tomorrow', 'what-time', 'where-are-you', 'when-finish', 'all-right-later', 'who-will-come', 'on-my-way'] },
  { id: 'invite', label: 'invite, ask permission, accept and decline', minimum: 5, drillIds: ['setting-off-coming', 'yes-coming', 'cannot-come', 'come-eat-with-us', 'may-enter'] },
  { id: 'catch-up', label: 'exchange news and ask what happened', minimum: 6, drillIds: ['how-road-went', 'were-you-away', 'still-not-slept', 'news-problem', 'really-then', 'tell-what-happened', 'dont-believe-it'] },
  { id: 'respond', label: 'keep a conversation moving', minimum: 4, drillIds: ['dont-know', 'really-then', 'tell-what-happened', 'dont-believe-it', 'well-thanks-you'] },
  { id: 'feelings', label: 'describe and understand everyday states', minimum: 6, drillIds: ['well-thanks-you', 'am-hungry', 'am-thirsty', 'tired-but-well', 'understand-afraid', 'miss-family', 'sorry-sympathy', 'are-you-well', 'hurts-here'] },
  { id: 'opinions', label: 'ask for an opinion, agree and disagree', minimum: 3, drillIds: ['what-think', 'dont-agree', 'think-you-right'] },
  { id: 'favours', label: 'ask, respond and give a simple instruction', minimum: 4, drillIds: ['bring-bread-salt', 'dont-forget-salt', 'give-bread', 'yes-take-it', 'can-help-me', 'yes-help-you'] },
  { id: 'care', label: 'show concern and respond to a problem', minimum: 4, drillIds: ['are-you-well', 'sorry-sympathy', 'be-careful', 'need-help', 'hurts-here'] },
  { id: 'routine', label: 'talk about food, sleep and work', minimum: 7, drillIds: ['have-eaten', 'have-slept', 'still-not-slept', 'sleep-good-night', 'at-work', 'when-finish', 'what-doing', 'on-my-way'] },
  { id: 'weather', label: 'understand ordinary weather talk', minimum: 3, drillIds: ['rained-yesterday', 'it-was-cold', 'when-rain-coming'] },
  { id: 'repair', label: 'repair a conversation', minimum: 4, drillIds: ['dont-know', 'dont-understand', 'speak-slowly', 'repeat-please', 'what-does-it-mean'] },
  { id: 'help', label: 'ask for and offer help', minimum: 2, drillIds: ['can-help-me', 'yes-help-you'] },
  { id: 'directions', label: 'ask and follow directions', minimum: 4, drillIds: ['where-market', 'where-guest-room', 'left-or-right', 'straight-then-right'] },
  { id: 'buy', label: 'make a simple purchase', minimum: 3, drillIds: ['have-bread', 'bread-salt-please', 'how-much-together'] },
  { id: 'food', label: 'eat, drink, offer and express preference', minimum: 8, drillIds: ['what-want', 'want-water', 'want-water-question', 'yes-thank-you', 'have-eaten', 'am-hungry', 'am-thirsty', 'come-eat-with-us', 'bon-appetit', 'like-tea', 'dont-like-coffee', 'coffee-please'] },
  { id: 'health', label: 'ask for care and describe pain', minimum: 3, drillIds: ['need-doctor', 'hurts-here', 'need-help'] },
  { id: 'lodging', label: 'ask for a room and a price', minimum: 3, drillIds: ['need-room-tonight', 'night-price', 'sleep-here'] },
  { id: 'daily-rhythm', label: 'greet, part and check in across a day', minimum: 6, drillIds: ['good-morning', 'good-evening', 'sleep-good-night', 'still-not-slept', 'all-right-later', 'good-luck-tomorrow'] },
  { id: 'hospitality', label: 'welcome a guest and close a visit warmly', minimum: 4, drillIds: ['welcome-enter', 'come-eat-with-us', 'thanks-come-again', 'thanks-goodbye'] },
  { id: 'thoughts-plans', label: 'share a feeling, idea or near-future concern', minimum: 4, drillIds: ['happy-going-home', 'have-an-idea', 'what-think', 'take-care-tonight', 'good-luck-tomorrow'] },
])

export const RECYCLED_EARLY_CHUNKS = Object.freeze([
  { al: 'si je', minimum: 2 },
  { al: 'po vij', minimum: 2 },
  { al: 'prit pak', minimum: 2 },
  { al: 'nuk e di', minimum: 2 },
  { al: 'shihemi nesër', minimum: 2 },
  { al: 'faleminderit', minimum: 12 },
  { al: 'të lutem', minimum: 6 },
  { al: 'mirëmëngjes', minimum: 4 },
  { al: 'mirëmbrëma', minimum: 6 },
  { al: 'në rregull', minimum: 2 },
])
