// Inflected noun surfaces are static authored language data. Keeping this table
// in its own cacheable module bounds the playable story-graph chunk without
// changing the dictionary or runtime validation contract.
export const NOUN_FORMS = {
  ar: [ /* gold */
    { al: 'ar', tag: 'indefNom', gloss: "gold" },
    { al: 'ari', tag: 'defNom', gloss: "the gold" },
    { al: 'arin', tag: 'defAcc', gloss: "the gold (object)" },
    { al: 'artë', tag: 'adj', gloss: "golden (të artë)" },
    { al: 'arta', tag: 'adjPl', gloss: "golden (të arta)" },
  ],
  arushe: [ /* bear */
    { al: 'arushë', tag: 'indefNom', gloss: "a bear" },
    { al: 'arusha', tag: 'defNom', gloss: "the bear" },
    { al: 'arushën', tag: 'defAcc', gloss: "the bear (object)" },
    { al: 'arushës', tag: 'defDat', gloss: "to/of the bear" },
  ],
  baba: [ /* father — hand */
    { al: 'baba', tag: 'indefNom', gloss: "a father" },
    { al: 'babai', tag: 'defNom', gloss: "the father" },
    { al: 'babi', tag: 'defNom', gloss: "dad" },
    { al: 'baban', tag: 'defAcc', gloss: "the father (object)" },
  ],
  baloz: [ /* sea-monster */
    { al: 'baloz', tag: 'indefNom', gloss: "a sea-monster" },
    { al: 'balozi', tag: 'defNom', gloss: "the sea-monster" },
    { al: 'balozin', tag: 'defAcc', gloss: "the sea-monster (object)" },
    { al: 'balozit', tag: 'defDat', gloss: "to/of the sea-monster" },
  ],
  bir: [ /* son */
    { al: 'bir', tag: 'indefNom', gloss: "a son" },
    { al: 'biri', tag: 'defNom', gloss: "the son" },
    { al: 'birin', tag: 'defAcc', gloss: "the son (object)" },
    { al: 'bijtë', tag: 'plDef', gloss: "the sons" },
    { al: 'birit', tag: 'defDat', gloss: "to/of the son" },
  ],
  bote: [ /* world */
    { al: 'botë', tag: 'indefNom', gloss: "a world" },
    { al: 'bota', tag: 'defNom', gloss: "the world" },
    { al: 'botën', tag: 'defAcc', gloss: "the world (object)" },
  ],
  burre: [ /* man */
    { al: 'burrë', tag: 'indefNom', gloss: "a man" },
    { al: 'burri', tag: 'defNom', gloss: "the man" },
    { al: 'burrin', tag: 'defAcc', gloss: "the man (object)" },
    { al: 'burrat', tag: 'plDef', gloss: "the men" },
    { al: 'burrave', tag: 'defDat', gloss: "to/of the men" },
  ],
  dallendyshe: [ /* swallow — hand */
    { al: 'dallëndyshe', tag: 'indefNom', gloss: "a swallow" },
    { al: 'dallëndyshen', tag: 'defAcc', gloss: "the swallow (object)" },
    { al: 'dallëndyshes', tag: 'defDat', gloss: "to/of the swallow" },
  ],
  dash: [ /* ram */
    { al: 'dash', tag: 'indefNom', gloss: "a ram" },
    { al: 'dashi', tag: 'defNom', gloss: "the ram" },
    { al: 'dashin', tag: 'defAcc', gloss: "the ram (object)" },
  ],
  dem: [ /* bull */
    { al: 'dem', tag: 'indefNom', gloss: "a bull" },
    { al: 'demi', tag: 'defNom', gloss: "the bull" },
    { al: 'demin', tag: 'defAcc', gloss: "the bull (object)" },
  ],
  dervish: [ /* dervish */
    { al: 'dervish', tag: 'indefNom', gloss: "a dervish" },
    { al: 'dervishi', tag: 'defNom', gloss: "the dervish" },
    { al: 'dervishin', tag: 'defAcc', gloss: "the dervish (object)" },
  ],
  det: [ /* sea */
    { al: 'det', tag: 'indefNom', gloss: "a sea" },
    { al: 'deti', tag: 'defNom', gloss: "the sea" },
    { al: 'detin', tag: 'defAcc', gloss: "the sea (object)" },
    { al: 'detit', tag: 'defDat', gloss: "to/of the sea" },
  ],
  dhelpra: [ /* fox */
    { al: 'dhelpër', tag: 'indefNom', gloss: "a fox" },
    { al: 'dhelpra', tag: 'defNom', gloss: "the fox" },
    { al: 'dhelprën', tag: 'defAcc', gloss: "the fox (object)" },
  ],
  dhi: [ /* goat */
    { al: 'dhi', tag: 'indefNom', gloss: "a goat" },
    { al: 'dhia', tag: 'defNom', gloss: "the goat" },
    { al: 'dhinë', tag: 'defAcc', gloss: "the goat (object)" },
    { al: 'dhitë', tag: 'plDef', gloss: "the goats" },
  ],
  diell: [ /* sun */
    { al: 'diell', tag: 'indefNom', gloss: "a sun" },
    { al: 'dielli', tag: 'defNom', gloss: "the sun" },
    { al: 'diellin', tag: 'defAcc', gloss: "the sun (object)" },
    { al: 'diellit', tag: 'defDat', gloss: "to/of the sun" },
  ],
  dite: [ /* day */
    { al: 'ditë', tag: 'indefNom', gloss: "a day" },
    { al: 'dita', tag: 'defNom', gloss: "the day" },
    { al: 'ditën', tag: 'defAcc', gloss: "the day (object)" },
    { al: 'ditës', tag: 'defDat', gloss: "of/to the day" },
    { al: 'ditët', tag: 'plDef', gloss: "the days" },
    { al: 'ditësh', tag: 'plAbl', gloss: "of days (pas shumë ditësh)" },
  ],
  djale: [ /* boy */
    { al: 'djalë', tag: 'indefNom', gloss: "a boy" },
    { al: 'djali', tag: 'defNom', gloss: "the boy" },
    { al: 'djalin', tag: 'defAcc', gloss: "the boy (object)" },
    { al: 'djem', tag: 'plIndef', gloss: "boys" },
    { al: 'djema', tag: 'plIndef', gloss: "boys" },
    { al: 'djemtë', tag: 'plDef', gloss: "the boys" },
    { al: "djal'", tag: 'elided', gloss: "boy («djal' i mëmës»)" },
    { al: 'djalit', tag: 'defDat', gloss: "to/of the boy" },
  ],
  djall: [ /* devil */
    { al: 'djall', tag: 'indefNom', gloss: "a devil" },
    { al: 'djalli', tag: 'defNom', gloss: "the devil" },
    { al: 'djallin', tag: 'defAcc', gloss: "the devil (object)" },
    { al: 'djallit', tag: 'defDat', gloss: "of the devil" },
  ],
  djep: [ /* cradle */
    { al: 'djep', tag: 'indefNom', gloss: "a cradle" },
    { al: 'djepin', tag: 'defAcc', gloss: "the cradle (object)" },
    { al: 'djepe', tag: 'plIndef', gloss: "cradles" },
    { al: 'djepet', tag: 'plDef', gloss: "the cradles" },
  ],
  dore: [ /* hand */
    { al: 'dorë', tag: 'indefNom', gloss: "a hand" },
    { al: 'dora', tag: 'defNom', gloss: "the hand" },
    { al: 'duar', tag: 'plIndef', gloss: "hands" },
    { al: 'duart', tag: 'plDef', gloss: "the hands" },
    { al: 'dorën', tag: 'defAcc', gloss: "the hand (object)" },
  ],
  dre: [ /* stag */
    { al: 'dre', tag: 'indefNom', gloss: "a stag" },
    { al: 'dreun', tag: 'defAcc', gloss: "the stag (object)" },
    { al: 'dreut', tag: 'defDat', gloss: "to/of the stag" },
  ],
  dreq: [ /* devil */
    { al: 'dreq', tag: 'indefNom', gloss: "a devil" },
    { al: 'dreqi', tag: 'defNom', gloss: "the devil" },
    { al: 'dreqin', tag: 'defAcc', gloss: "the devil (object)" },
  ],
  drite: [ /* light */
    { al: 'dritë', tag: 'indefNom', gloss: "a light" },
    { al: 'drita', tag: 'defNom', gloss: "the light" },
    { al: 'dritën', tag: 'defAcc', gloss: "the light (object)" },
  ],
  ere: [ /* wind */
    { al: 'erë', tag: 'indefNom', gloss: "a wind" },
    { al: 'era', tag: 'defNom', gloss: "the wind" },
    { al: 'erën', tag: 'defAcc', gloss: "the wind (object)" },
  ],
  erresire: [ /* darkness */
    { al: 'errësirë', tag: 'indefNom', gloss: "darkness" },
    { al: 'errësira', tag: 'defNom', gloss: "the darkness" },
    { al: 'errësirën', tag: 'defAcc', gloss: "the darkness (object)" },
  ],
  femije: [ /* child */
    { al: 'fëmijë', tag: 'indefNom', gloss: "a child" },
    { al: 'fëmija', tag: 'defNom', gloss: "the child" },
    { al: 'fëmijën', tag: 'defAcc', gloss: "the child (object)" },
    { al: 'fëmijës', tag: 'defDat', gloss: "to/of the child" },
    { al: 'fëmijët', tag: 'plDef', gloss: "the children" },
  ],
  flake: [ /* flame */
    { al: 'flakë', tag: 'indefNom', gloss: "a flame" },
    { al: 'flaka', tag: 'defNom', gloss: "the flame" },
    { al: 'flakën', tag: 'defAcc', gloss: "the flame (object)" },
  ],
  fund: [ /* end */
    { al: 'fund', tag: 'indefNom', gloss: "an end" },
    { al: 'fundi', tag: 'defNom', gloss: "the end" },
    { al: 'fundin', tag: 'defAcc', gloss: "the end (object)" },
    { al: 'fundit', tag: 'defDat', gloss: "to/of the end" },
  ],
  fuqi: [ /* power */
    { al: 'fuqi', tag: 'indefNom', gloss: "power" },
    { al: 'fuqia', tag: 'defNom', gloss: "the power" },
    { al: 'fuqinë', tag: 'defAcc', gloss: "the power (object)" },
  ],
  gjak: [ /* blood */
    { al: 'gjak', tag: 'indefNom', gloss: "blood" },
    { al: 'gjaku', tag: 'defNom', gloss: "the blood" },
    { al: 'gjakun', tag: 'defAcc', gloss: "the blood (object)" },
  ],
  gjarper: [ /* serpent */
    { al: 'gjarpër', tag: 'indefNom', gloss: "a serpent" },
    { al: 'gjarpri', tag: 'defNom', gloss: "the serpent" },
    { al: 'gjarprin', tag: 'defAcc', gloss: "the serpent (object)" },
    { al: 'gjarprit', tag: 'defDat', gloss: "to/of the serpent" },
    { al: 'gjarpërinj', tag: 'plIndef', gloss: "serpents" },
    { al: 'gjarpërinjtë', tag: 'plDef', gloss: "the serpents" },
  ],
  gje: [ /* thing — hand */
    { al: 'gjë', tag: 'indefNom', gloss: "a thing" },
    { al: 'gjëra', tag: 'plIndef', gloss: "things" },
    { al: 'gjërat', tag: 'plDef', gloss: "the things" },
  ],
  grua: [ /* woman */
    { al: 'grua', tag: 'indefNom', gloss: "a woman" },
    { al: 'gruaja', tag: 'defNom', gloss: "the woman" },
    { al: 'gruan', tag: 'defAcc', gloss: "the woman (object)" },
    { al: 'gruas', tag: 'defDat', gloss: "to/of the woman" },
    { al: 'gratë', tag: 'plDef', gloss: "the women" },
    { al: 'gruaje', tag: 'ablIndef', gloss: "of a woman" },
  ],
  gur: [ /* stone */
    { al: 'gur', tag: 'indefNom', gloss: "a stone" },
    { al: 'guri', tag: 'defNom', gloss: "the stone" },
    { al: 'gurin', tag: 'defAcc', gloss: "the stone (object)" },
    { al: 'gurë', tag: 'plIndef', gloss: "stones" },
    { al: 'gurët', tag: 'plDef', gloss: "the stones" },
    { al: 'gurëve', tag: 'defDat', gloss: "to/of the stones" },
  ],
  hekur: [ /* iron */
    { al: 'hekur', tag: 'indefNom', gloss: "iron" },
    { al: 'hekuri', tag: 'defNom', gloss: "the iron" },
    { al: 'hekurin', tag: 'defAcc', gloss: "the iron (object)" },
  ],
  hendek: [ /* moat */
    { al: 'hendek', tag: 'indefNom', gloss: "a moat" },
    { al: 'hendeku', tag: 'defNom', gloss: "the moat" },
    { al: 'hendekun', tag: 'defAcc', gloss: "the moat (object)" },
  ],
  hene: [ /* moon */
    { al: 'hënë', tag: 'indefNom', gloss: "a moon" },
    { al: 'hëna', tag: 'defNom', gloss: "the moon" },
    { al: 'hënën', tag: 'defAcc', gloss: "the moon (object)" },
    { al: 'hënës', tag: 'defDat', gloss: "to/of the moon" },
  ],
  hije: [ /* shadow */
    { al: 'hije', tag: 'indefNom', gloss: "a shadow" },
    { al: 'hija', tag: 'defNom', gloss: "the shadow" },
    { al: 'hijen', tag: 'defAcc', gloss: "the shadow (object)" },
    { al: 'hijet', tag: 'plDef', gloss: "the shadows" },
  ],
  kale: [ /* horse */
    { al: 'kalë', tag: 'indefNom', gloss: "a horse" },
    { al: 'kali', tag: 'defNom', gloss: "the horse" },
    { al: 'kalin', tag: 'defAcc', gloss: "the horse (object)" },
    { al: 'kalit', tag: 'defDat', gloss: "to/of the horse" },
    { al: 'kuajt', tag: 'plDef', gloss: "the horses" },
    { al: 'kuaj', tag: 'plIndef', gloss: "horses" },
  ],
  kapidan: [ /* captain */
    { al: 'kapidan', tag: 'indefNom', gloss: "a captain" },
    { al: 'kapidani', tag: 'defNom', gloss: "the captain" },
    { al: 'kapidanin', tag: 'defAcc', gloss: "the captain (object)" },
  ],
  karkanxholl: [ /* iron-clad revenant */
    { al: 'karkanxholl', tag: 'indefNom', gloss: "an iron-clad revenant" },
    { al: 'karkanxholli', tag: 'defNom', gloss: "the iron-clad revenant" },
    { al: 'karkanxhollin', tag: 'defAcc', gloss: "the iron-clad revenant (object)" },
  ],
  katallan: [ /* one-eyed giant */
    { al: 'katallan', tag: 'indefNom', gloss: "an one-eyed giant" },
    { al: 'katallani', tag: 'defNom', gloss: "the one-eyed giant" },
    { al: 'katallanin', tag: 'defAcc', gloss: "the one-eyed giant (object)" },
  ],
  kazan: [ /* cauldron */
    { al: 'kazan', tag: 'indefNom', gloss: "a cauldron" },
    { al: 'kazani', tag: 'defNom', gloss: "the cauldron" },
    { al: 'kazanin', tag: 'defAcc', gloss: "the cauldron (object)" },
  ],
  kembe: [ /* legs — hand */
    { al: 'këmbë', tag: 'indefNom', gloss: "a leg" },
    { al: 'këmbën', tag: 'defAcc', gloss: "the leg (object)" },
    { al: 'këmba', tag: 'defNom', gloss: "the leg/foot" },
    { al: 'këmbët', tag: 'plDef', gloss: "the legs/feet" },
  ],
  kemishe: [ /* caul */
    { al: 'këmishë', tag: 'indefNom', gloss: "a caul" },
    { al: 'këmishën', tag: 'defAcc', gloss: "the caul (object)" },
  ],
  kishe: [ /* church */
    { al: 'kishë', tag: 'indefNom', gloss: "a church" },
    { al: 'kisha', tag: 'defNom', gloss: "the church" },
    { al: 'kishën', tag: 'defAcc', gloss: "the church (object)" },
  ],
  koke: [ /* head */
    { al: 'kokë', tag: 'indefNom', gloss: "a head" },
    { al: 'kokën', tag: 'defAcc', gloss: "the head (object)" },
    { al: 'koka', tag: 'defNom', gloss: "the head" },
    { al: 'kokat', tag: 'plDef', gloss: "the heads" },
  ],
  krajl: [ /* Slav king */
    { al: 'krajl', tag: 'indefNom', gloss: "a Slav king" },
    { al: 'krajli', tag: 'defNom', gloss: "the Slav king" },
    { al: 'krajlin', tag: 'defAcc', gloss: "the Slav king (object)" },
    { al: 'krajlit', tag: 'defDat', gloss: "to/of the Slav king" },
  ],
  krua: [ /* spring */
    { al: 'krua', tag: 'indefNom', gloss: "a spring" },
    { al: 'kroi', tag: 'defNom', gloss: "the spring" },
    { al: 'kroin', tag: 'defAcc', gloss: "the spring (object)" },
    { al: 'kroit', tag: 'defDat', gloss: "to/of the spring" },
  ],
  kukudh: [ /* miser-ghost */
    { al: 'kukudh', tag: 'indefNom', gloss: "a miser-ghost" },
    { al: 'kukudhi', tag: 'defNom', gloss: "the miser-ghost" },
    { al: 'kukudhin', tag: 'defAcc', gloss: "the miser-ghost (object)" },
  ],
  kulle: [ /* tower */
    { al: 'kullë', tag: 'indefNom', gloss: "a tower" },
    { al: 'kulla', tag: 'defNom', gloss: "the tower" },
    { al: 'kullën', tag: 'defAcc', gloss: "the tower (object)" },
    { al: 'kullës', tag: 'defDat', gloss: "to/of the tower" },
    { al: 'kullat', tag: 'plDef', gloss: "the towers" },
  ],
  kuzhinier: [ /* cook */
    { al: 'kuzhinier', tag: 'indefNom', gloss: "a cook" },
    { al: 'kuzhinieri', tag: 'defNom', gloss: "the cook" },
    { al: 'kuzhinierin', tag: 'defAcc', gloss: "the cook (object)" },
    { al: 'kuzhinierit', tag: 'defDat', gloss: "to/of the cook" },
  ],
  lahute: [ /* lute */
    { al: 'lahutë', tag: 'indefNom', gloss: "a lute" },
    { al: 'lahuta', tag: 'defNom', gloss: "the lute" },
    { al: 'lahutën', tag: 'defAcc', gloss: "the lute (object)" },
  ],
  liber: [ /* book */
    { al: 'libër', tag: 'indefNom', gloss: "a book" },
    { al: 'libri', tag: 'defNom', gloss: "the book" },
    { al: 'librin', tag: 'defAcc', gloss: "the book (object)" },
  ],
  lot: [ /* tears — hand */
    { al: 'lot', tag: 'indefNom', gloss: "a tear" },
    { al: 'lotët', tag: 'plDef', gloss: "the tears" },
  ],
  lugat: [ /* revenant */
    { al: 'lugat', tag: 'indefNom', gloss: "a revenant" },
    { al: 'lugati', tag: 'defNom', gloss: "the revenant" },
    { al: 'lugatin', tag: 'defAcc', gloss: "the revenant (object)" },
  ],
  lume: [ /* river — hand */
    { al: 'lumë', tag: 'indefNom', gloss: "a river" },
    { al: 'lumi', tag: 'defNom', gloss: "the river" },
    { al: 'lumin', tag: 'defAcc', gloss: "the river (object)" },
    { al: 'lumit', tag: 'defDat', gloss: "to/of the river" },
  ],
  mbreteresha: [ /* queen */
    { al: 'mbretëreshë', tag: 'indefNom', gloss: "a queen" },
    { al: 'mbretëresha', tag: 'defNom', gloss: "the queen" },
    { al: 'mbretëreshën', tag: 'defAcc', gloss: "the queen (object)" },
    { al: 'mbretëreshës', tag: 'defDat', gloss: "to/of the queen" },
  ],
  mik: [ /* friend — hand */
    { al: 'mik', tag: 'indefNom', gloss: "a friend" },
    { al: 'mike', tag: 'indefNom', gloss: "a friend (female)" },
    { al: 'miku', tag: 'defNom', gloss: "the friend" },
    { al: 'mikun', tag: 'defAcc', gloss: "the friend (object)" },
    { al: 'mikut', tag: 'defDat', gloss: "to/of the friend" },
    { al: 'miqtë', tag: 'plDef', gloss: "the guests" },
  ],
  familje: [ /* family */
    { al: 'familje', tag: 'indefNom', gloss: "a family" },
    { al: 'familja', tag: 'defNom', gloss: "the family" },
    { al: 'familjen', tag: 'defAcc', gloss: "the family (object)" },
    { al: 'familjes', tag: 'defDat', gloss: "to/of the family" },
  ],
  mjeshter: [ /* master */
    { al: 'mjeshtër', tag: 'indefNom', gloss: "a master" },
    { al: 'mjeshtri', tag: 'defNom', gloss: "the master" },
    { al: 'mjeshtrin', tag: 'defAcc', gloss: "the master (object)" },
  ],
  motra: [ /* sister */
    { al: 'motër', tag: 'indefNom', gloss: "a sister" },
    { al: 'motra', tag: 'defNom', gloss: "the sister" },
    { al: 'motrën', tag: 'defAcc', gloss: "the sister (object)" },
    { al: 'motrës', tag: 'defDat', gloss: "to/of the sister" },
    { al: 'motrat', tag: 'plDef', gloss: "the sisters" },
  ],
  mulli: [ /* mill — hand */
    { al: 'mulli', tag: 'indefNom', gloss: "a mill" },
    { al: 'mulliri', tag: 'defNom', gloss: "the mill" },
    { al: 'mullirin', tag: 'defAcc', gloss: "the mill (object)" },
    { al: 'mullirit', tag: 'defDat', gloss: "to/of the mill" },
  ],
  mur: [ /* wall */
    { al: 'mur', tag: 'indefNom', gloss: "a wall" },
    { al: 'muri', tag: 'defNom', gloss: "the wall" },
    { al: 'murin', tag: 'defAcc', gloss: "the wall (object)" },
  ],
  nene: [ /* mother — hand */
    { al: 'nënë', tag: 'indefNom', gloss: "a mother" },
    { al: 'nëna', tag: 'defNom', gloss: "the mother" },
    { al: 'nënën', tag: 'defAcc', gloss: "the mother (object)" },
    { al: 'mëmës', tag: 'defDatTosk', gloss: "of the mother (Tosk «mëmës»)" },
    { al: 'nënës', tag: 'defDat', gloss: "to/of the mother" },
  ],
  njeri: [ /* person — hand */
    { al: 'njeri', tag: 'indefNom', gloss: "a person" },
    { al: 'njeriu', tag: 'defNom', gloss: "the person" },
    { al: 'njeriun', tag: 'defAcc', gloss: "the person (object)" },
    { al: 'njeriut', tag: 'defDat', gloss: "to/of the person" },
    { al: 'njerëz', tag: 'plIndef', gloss: "people" },
    { al: 'njerëzit', tag: 'plDef', gloss: "the people" },
  ],
  nuse: [ /* bride — hand */
    { al: 'nuse', tag: 'indefNom', gloss: "a bride" },
    { al: 'nusja', tag: 'defNom', gloss: "the bride" },
    { al: 'nusen', tag: 'defAcc', gloss: "the bride (object)" },
    { al: 'nuses', tag: 'defDat', gloss: "to/of the bride" },
    { al: 'nuseve', tag: 'plDef', gloss: "the brides" },
  ],
  oda: [ /* guest-room */
    { al: 'odë', tag: 'indefNom', gloss: 'a guest-room' },
    { al: 'oda', tag: 'defNom', gloss: 'the guest-room' },
    { al: 'odën', tag: 'defAcc', gloss: 'the guest-room (object)' },
    { al: 'odës', tag: 'defDat', gloss: 'to/of the guest-room' },
  ],
  pallat: [ /* palace */
    { al: 'pallat', tag: 'indefNom', gloss: "a palace" },
    { al: 'pallati', tag: 'defNom', gloss: "the palace" },
    { al: 'pallatit', tag: 'defDat', gloss: 'of/to the palace' },
    { al: 'pallatin', tag: 'defAcc', gloss: "the palace (object)" },
  ],
  pate: [ /* goose — hand */
    { al: 'patë', tag: 'indefNom', gloss: "a goose" },
    { al: 'patat', tag: 'plDef', gloss: "the geese" },
    { al: 'patave', tag: 'plDef', gloss: "the geese (to/of)" },
  ],
  peme: [ /* tree */
    { al: 'pemë', tag: 'indefNom', gloss: "a tree" },
    { al: 'pemën', tag: 'defAcc', gloss: "the tree (object)" },
    { al: 'pemët', tag: 'plDef', gloss: "the trees" },
    { al: 'pemëve', tag: 'defDat', gloss: "to/of the trees" },
  ],
  pende: [ /* feather */
    { al: 'pendë', tag: 'indefNom', gloss: "a feather" },
    { al: 'penda', tag: 'defNom', gloss: "the feather" },
    { al: 'pendën', tag: 'defAcc', gloss: "the feather (object)" },
  ],
  plake: [ /* old woman */
    { al: 'plakë', tag: 'indefNom', gloss: "an old woman" },
    { al: 'plaka', tag: 'defNom', gloss: "the old woman" },
    { al: 'plakën', tag: 'defAcc', gloss: "the old woman (object)" },
    { al: 'plakës', tag: 'defDat', gloss: "to the old woman" },
  ],
  prift: [ /* priest */
    { al: 'prift', tag: 'indefNom', gloss: "a priest" },
    { al: 'prifti', tag: 'defNom', gloss: "the priest" },
    { al: 'priftërinjtë', tag: 'plDef', gloss: 'the priests' },
    { al: 'priftin', tag: 'defAcc', gloss: "the priest (object)" },
  ],
  pune: [ /* work */
    { al: 'punë', tag: 'indefNom', gloss: "a work" },
    { al: 'pune', tag: 'indefDat', gloss: "of work" },
    { al: 'puna', tag: 'defNom', gloss: "the work" },
    { al: 'punën', tag: 'defAcc', gloss: "the work (object)" },
  ],
  pus: [ /* well */
    { al: 'pus', tag: 'indefNom', gloss: "a well" },
    { al: 'pusi', tag: 'defNom', gloss: "the well" },
    { al: 'pusin', tag: 'defAcc', gloss: "the well (object)" },
    { al: 'pusit', tag: 'defDat', gloss: "to/of the well" },
  ],
  qen: [ /* dog */
    { al: 'qen', tag: 'indefNom', gloss: "a dog" },
    { al: 'qeni', tag: 'defNom', gloss: "the dog" },
    { al: 'qenin', tag: 'defAcc', gloss: "the dog (object)" },
    { al: 'qenit', tag: 'defDat', gloss: "to/of the dog" },
  ],
  qengj: [ /* lamb */
    { al: 'qengj', tag: 'indefNom', gloss: "a lamb" },
    { al: 'qengji', tag: 'defNom', gloss: "the lamb" },
    { al: 'qengjit', tag: 'defDat', gloss: "to/of the lamb" },
  ],
  qilim: [ /* rug */
    { al: 'qilim', tag: 'indefNom', gloss: "a rug" },
    { al: 'qilimi', tag: 'defNom', gloss: "the rug" },
    { al: 'qilimin', tag: 'defAcc', gloss: "the rug (object)" },
  ],
  qumesht: [ /* milk */
    { al: 'qumësht', tag: 'indefNom', gloss: "milk" },
    { al: 'qumeshti', tag: 'defNom', gloss: "the milk" },
    { al: 'qumështin', tag: 'defAcc', gloss: "the milk (object)" },
  ],
  qytet: [ /* city */
    { al: 'qytet', tag: 'indefNom', gloss: "a city" },
    { al: 'qyteti', tag: 'defNom', gloss: "the city" },
    { al: 'qytetin', tag: 'defAcc', gloss: "the city (object)" },
    { al: 'qytetit', tag: 'defDat', gloss: "of/from the city" },
  ],
  roje: [ /* guard */
    { al: 'roje', tag: 'indefNom', gloss: "a guard" },
    { al: 'roja', tag: 'defNom', gloss: "the guard" },
    { al: 'rojen', tag: 'defAcc', gloss: "the guard (object)" },
    { al: 'rojet', tag: 'plDef', gloss: "the guards" },
    { al: 'rojet', tag: 'plDef', gloss: "the guards" },
  ],
  rrobe: [ /* dress */
    { al: 'rrobë', tag: 'indefNom', gloss: "a dress" },
    { al: 'rroba', tag: 'defNom', gloss: "the dress" },
    { al: 'rrobën', tag: 'defAcc', gloss: "the dress (object)" },
    { al: 'rrobat', tag: 'plDef', gloss: "the dresses" },
  ],
  sherbetore: [ /* servant */
    { al: 'shërbëtore', tag: 'indefNom', gloss: "a servant" },
    { al: 'sherbetorja', tag: 'defNom', gloss: "the servant" },
    { al: 'sherbetoren', tag: 'defAcc', gloss: "the servant (object)" },
  ],
  shpate: [ /* sword */
    { al: 'shpatë', tag: 'indefNom', gloss: "a sword" },
    { al: 'shpata', tag: 'defNom', gloss: "the sword" },
    { al: 'shpatën', tag: 'defAcc', gloss: "the sword (object)" },
  ],
  shpelle: [ /* cave */
    { al: 'shpellë', tag: 'indefNom', gloss: "a cave" },
    { al: 'shpella', tag: 'defNom', gloss: "the cave" },
    { al: 'shpellën', tag: 'defAcc', gloss: "the cave (object)" },
    { al: 'shpellës', tag: 'defDat', gloss: "of/from the cave" },
  ],
  shqiponje: [ /* eagle */
    { al: 'shqiponjë', tag: 'indefNom', gloss: "an eagle" },
    { al: 'shqiponja', tag: 'defNom', gloss: "the eagle" },
    { al: 'shqiponjën', tag: 'defAcc', gloss: "the eagle (object)" },
    { al: 'shqiponjës', tag: 'defDat', gloss: "to/of the eagle" },
    { al: 'shqiponjat', tag: 'plDef', gloss: "the eagles" },
  ],
  shtrige: [ /* witch */
    { al: 'shtrigë', tag: 'indefNom', gloss: "a witch" },
    { al: 'shtriga', tag: 'defNom', gloss: "the witch" },
    { al: 'shtrigën', tag: 'defAcc', gloss: "the witch (object)" },
  ],
  sy: [ /* eyes — hand */
    { al: 'sy', tag: 'indefNom', gloss: "an eye" },
    { al: 'syri', tag: 'defNom', gloss: "the eye" },
    { al: 'syrin', tag: 'defAcc', gloss: "the eye (object)" },
    { al: 'syve', tag: 'plDat', gloss: 'of/to the eyes' },
    { al: 'sytë', tag: 'plDef', gloss: "the eyes" },
  ],
  toke: [ /* ground */
    { al: 'tokë', tag: 'indefNom', gloss: "a ground" },
    { al: 'toka', tag: 'defNom', gloss: "the ground" },
    { al: 'tokën', tag: 'defAcc', gloss: "the ground (object)" },
    { al: 'dheut', tag: 'defDat', gloss: "to/of the ground" },
  ],
  treg: [ /* market */
    { al: 'treg', tag: 'indefNom', gloss: "a market" },
    { al: 'tregu', tag: 'defNom', gloss: "the market" },
    { al: 'tregun', tag: 'defAcc', gloss: "the market (object)" },
    { al: 'tregut', tag: 'defDat', gloss: "to/of the market" },
  ],
  udhetar: [ /* traveller */
    { al: 'udhëtar', tag: 'indefNom', gloss: "a traveller" },
    { al: 'udhëtari', tag: 'defNom', gloss: "the traveller" },
    { al: 'udhëtarin', tag: 'defAcc', gloss: "the traveller (object)" },
    { al: 'udhëtarë', tag: 'plIndef', gloss: "travellers" },
    { al: 'udhëtarët', tag: 'plDef', gloss: "the travellers" },
  ],
  uje: [ /* water */
    { al: 'ujë', tag: 'indefNom', gloss: "water" },
    { al: 'uji', tag: 'defNom', gloss: "the water" },
    { al: 'ujin', tag: 'defAcc', gloss: "the water (object)" },
    { al: 'ujit', tag: 'defDat', gloss: "to/of the water" },
  ],
  ujk: [ /* wolf */
    { al: 'ujk', tag: 'indefNom', gloss: "a wolf" },
    { al: 'ujku', tag: 'defNom', gloss: "the wolf" },
    { al: 'ujkun', tag: 'defAcc', gloss: "the wolf (object)" },
    { al: 'ujkut', tag: 'defDat', gloss: "to/of the wolf" },
  ],
  ure: [ /* bridge */
    { al: 'urë', tag: 'indefNom', gloss: "a bridge" },
    { al: 'ura', tag: 'defNom', gloss: "the bridge" },
    { al: 'urën', tag: 'defAcc', gloss: "the bridge (object)" },
    { al: 'urës', tag: 'defDat', gloss: "behind/of the bridge" },
  ],
  tabak: [ /* tanner */
    { al: 'tabak', tag: 'indefNom', gloss: "a tanner" },
    { al: 'tabaku', tag: 'defNom', gloss: "the tanner" },
    { al: 'tabakun', tag: 'defAcc', gloss: "the tanner (object)" },
    { al: 'tabakët', tag: 'plDef', gloss: "the tanners" },
    { al: 'tabakëve', tag: 'defDat', gloss: "to/of the tanners" },
  ],
  vajze: [ /* maiden */
    { al: 'vajzë', tag: 'indefNom', gloss: "a maiden" },
    { al: 'vajza', tag: 'defNom', gloss: "the maiden" },
    { al: 'vajzën', tag: 'defAcc', gloss: "the maiden (object)" },
    { al: 'vajzës', tag: 'defDat', gloss: "to/of the maiden" },
    { al: 'vajzat', tag: 'plDef', gloss: "the maidens" },
  ],
  varr: [ /* grave */
    { al: 'varr', tag: 'indefNom', gloss: "a grave" },
    { al: 'varrin', tag: 'defAcc', gloss: "the grave (object)" },
    { al: 'varrit', tag: 'defDat', gloss: "to/of the grave" },
    { al: 'varret', tag: 'plDef', gloss: "the graves" },
    { al: 'varri', tag: 'defNom', gloss: "the grave" },
    { al: 'varre', tag: 'plIndef', gloss: "graves" },
  ],
  vella: [ /* brother — hand */
    { al: 'vëlla', tag: 'indefNom', gloss: "a brother" },
    { al: 'vëllai', tag: 'defNom', gloss: "the brother" },
    { al: 'vëllait', tag: 'defDat', gloss: "to/of the brother" },
    { al: 'vëllezër', tag: 'plIndef', gloss: "brothers" },
    { al: 'vëllezërit', tag: 'plDef', gloss: "the brothers" },
    { al: 'vëllezërve', tag: 'plDat', gloss: "to/of the brothers" },
    { al: 'vëllanë', tag: 'defAcc', gloss: "the brother (object)" },
  ],
  vend: [ /* place */
    { al: 'vend', tag: 'indefNom', gloss: "a place" },
    { al: 'vendi', tag: 'defNom', gloss: "the place" },
    { al: 'vendin', tag: 'defAcc', gloss: "the place (object)" },
    { al: 'vendet', tag: 'plDef', gloss: "the places" },
    { al: 'vende', tag: 'plIndef', gloss: "places" },
  ],
  vit: [ /* year */
    { al: 'vit', tag: 'indefNom', gloss: "a year" },
    { al: 'viti', tag: 'defNom', gloss: "the year" },
    { al: 'vjet', tag: 'plDef', gloss: "the years" },
    { al: 'vite', tag: 'plIndef', gloss: "years" },
  ],
  vitore: [ /* house-serpent */
    { al: 'vitore', tag: 'indefNom', gloss: "a house-serpent" },
    { al: 'vitorja', tag: 'defNom', gloss: "the house-serpent" },
    { al: 'vitoren', tag: 'defAcc', gloss: "the house-serpent (object)" },
  ],
  zane: [ /* mountain-fairy */
    { al: 'zanë', tag: 'indefNom', gloss: "a mountain-fairy" },
    { al: 'zana', tag: 'defNom', gloss: "the mountain-fairy" },
    { al: 'zanën', tag: 'defAcc', gloss: "the mountain-fairy (object)" },
    { al: 'zanës', tag: 'defDat', gloss: "to/of the mountain-fairy" },
    { al: 'zanat', tag: 'plDef', gloss: "the mountain-fairies" },
    { al: 'zanave', tag: 'plDat', gloss: "to/of the mountain-fairies" },
  ],
  zjarr: [ /* fire */
    { al: 'zjarr', tag: 'indefNom', gloss: "a fire" },
    { al: 'zjarri', tag: 'defNom', gloss: "the fire" },
    { al: 'zjarrin', tag: 'defAcc', gloss: "the fire (object)" },
    { al: 'zjarrit', tag: 'defDat', gloss: "to/of the fire" },
    { al: 'zjarre', tag: 'plIndef', gloss: "fires" },
  ],
  zog: [ /* chick */
    { al: 'zog', tag: 'indefNom', gloss: "a chick" },
    { al: 'zogu', tag: 'defNom', gloss: "the chick" },
    { al: 'zogun', tag: 'defAcc', gloss: "the chick (object)" },
    { al: 'zogjtë', tag: 'plDef', gloss: "the birds" },
  ],
}
