// Reviewed situations for meanings that cannot be learned safely from a bare
// written form. The Albanian line is the learner's evidence; English is a
// post-attempt gloss or the cue for the later controlled-retrieval direction.
//
// `review.cueTokens` names the visible Albanian evidence outside the target.
// For homographs, `contrastIds` and `review.contrastRationales` must account for
// every other dictionary sense with the same spelling. The exhaustive audit
// keeps these declarations and every emitted context question in lockstep.

const reviewed = ({
  al,
  en,
  focus,
  retrievalEn,
  distractorIds,
  retrievalDistractorIds,
  contrastIds = [],
  cueTokens,
  rationale,
  contrastRationales = {},
  defensibleAlternativeRationales = {},
  register = 'everyday-standard',
  ...optional
}) => Object.freeze({
  al,
  en,
  focus,
  quality: 'sense-discriminating',
  register,
  cueTokens: Object.freeze(cueTokens),
  rationale,
  contrastIds: Object.freeze(contrastIds),
  contrastRationales: Object.freeze(contrastRationales),
  defensibleAlternativeRationales: Object.freeze(Object.fromEntries(
    Object.entries(defensibleAlternativeRationales).map(([direction, rationales]) => [
      direction,
      Object.freeze({ ...rationales }),
    ]),
  )),
  distractorIds: Object.freeze(distractorIds),
  retrieval: Object.freeze({
    en: retrievalEn,
    reviewed: true,
    distractorIds: Object.freeze(retrievalDistractorIds),
  }),
  ...optional,
})

export const REVIEWED_WORD_CONTEXTS = Object.freeze({
  dhe: reviewed({
    al: 'A do bukë dhe djathë?',
    en: 'Do you want bread __ cheese?',
    focus: 'dhe',
    retrievalEn: 'Do you want bread and cheese?',
    distractorIds: ['dhe_gave', 'ose', 'edhe'],
    retrievalDistractorIds: ['ose', 'pa', 'por'],
    defensibleAlternativeRationales: {
      en2al: {
        me: 'Bukë me djathë is also a natural request for bread with cheese, so the short English cue cannot make me unequivocally wrong.',
      },
    },
    contrastIds: ['dhe_gave'],
    cueTokens: ['bukë', 'djathë'],
    rationale: 'Between two foods, dhe joins equal alternatives in a natural offer.',
    contrastRationales: { dhe_gave: 'The surrounding noun phrases leave no verb slot for the past-tense form “gave”.' },
  }),
  te_link: reviewed({
    al: 'Ata janë miq të fshatit.',
    en: 'They are friends __ the village.',
    focus: 'të',
    retrievalEn: 'They are friends of the village.',
    distractorIds: ['te_subj', 'te_obj', 'i_link'],
    retrievalDistractorIds: ['i_link', 'e_link', 'nga'],
    contrastIds: ['te_subj', 'te_obj'],
    cueTokens: ['miq', 'fshatit'],
    rationale: 'Miq and the genitive fshatit make të the linking article in a noun phrase.',
    contrastRationales: {
      te_subj: 'No following verb is available for the subjunctive marker.',
      te_obj: 'The line already has an explicit subject and no verb that could take “you” as its object.',
    },
  }),
  te_subj: reviewed({
    al: 'Dua të pi ujë.',
    en: 'I want __ drink water.',
    focus: 'të',
    retrievalEn: 'I want to drink water.',
    distractorIds: ['te_link', 'te_obj', 'do_fut'],
    retrievalDistractorIds: ['do_fut', 'mund', 'mos'],
    contrastIds: ['te_link', 'te_obj'],
    cueTokens: ['Dua', 'pi'],
    rationale: 'Between the modal-like dua and the following verb pi, të introduces the dependent verb.',
    contrastRationales: {
      te_link: 'Pi is a verb, not a genitive noun phrase to be linked.',
      te_obj: 'Të does not stand for a person here; pi supplies the action it introduces.',
    },
  }),
  te_obj: reviewed({
    al: 'Ajo të pret te ura.',
    en: 'She waits for __ at the bridge.',
    focus: 'të',
    retrievalEn: 'She waits for you at the bridge.',
    distractorIds: ['te_link', 'te_subj', 'e_obj'],
    retrievalDistractorIds: ['e_obj', 'me_obj', 'na'],
    contrastIds: ['te_link', 'te_subj'],
    cueTokens: ['Ajo', 'pret'],
    rationale: 'Immediately before pret, të names the person being waited for.',
    contrastRationales: {
      te_link: 'Pret is a verb, so this is not a noun-linking article.',
      te_subj: 'There is no preceding modal and të is followed by a finite verb, not a dependent verb form.',
    },
  }),
  i_art: reviewed({
    al: 'Ujku është i madh.',
    en: 'The wolf is big; Albanian uses the __ before this adjective.',
    focus: 'i',
    retrievalEn: 'The wolf is big.',
    distractorIds: ['i_link', 'i_obj', 'e_art'],
    retrievalDistractorIds: ['e_art', 'me_more', 'shume'],
    contrastIds: ['i_link', 'i_obj'],
    cueTokens: ['Ujku', 'madh'],
    rationale: 'After është and before the masculine adjective madh, i is the adjective article.',
    contrastRationales: {
      i_link: 'Madh is an adjective here, not a possessor noun phrase.',
      i_obj: 'No recipient meaning is possible between është and madh.',
    },
  }),
  i_link: reviewed({
    al: 'Ky është çelësi i shtëpisë.',
    en: 'This is the key __ the house.',
    focus: 'i',
    retrievalEn: 'This is the key to the house.',
    distractorIds: ['i_art', 'i_obj', 'e_link'],
    retrievalDistractorIds: ['e_link', 'te_link', 'per'],
    contrastIds: ['i_art', 'i_obj'],
    cueTokens: ['çelësi', 'shtëpisë'],
    rationale: 'Between çelësi and genitive shtëpisë, i links the possessed noun to its owner.',
    contrastRationales: {
      i_art: 'Shtëpisë is a noun in the genitive/dative form, not an adjective.',
      i_obj: 'There is no verb for an indirect-object clitic to attach to.',
    },
  }),
  fshat: reviewed({
    al: 'Po shkoj në fshat.',
    en: 'I am going to the __.',
    focus: 'fshat',
    retrievalEn: 'I am going to the village.',
    distractorIds: ['qytet', 'shtepi', 'treg'],
    retrievalDistractorIds: ['qytet', 'shtepi', 'treg'],
    cueTokens: ['shkoj', 'në'],
    rationale: 'The movement phrase supplies a lived destination context for the place noun.',
  }),
  kashte: reviewed({
    al: 'Po shtrojmë kashtë për kafshët.',
    en: 'We are spreading __ for the animals.',
    focus: 'kashtë',
    retrievalEn: 'We are spreading straw for the animals.',
    distractorIds: ['sane', 'bar', 'dru'],
    retrievalDistractorIds: ['sane', 'bar', 'dru'],
    cueTokens: ['shtrojmë', 'kafshët'],
    rationale: 'Spreading material as bedding for animals distinguishes straw from feed and wood.',
  }),
  sane: reviewed({
    al: 'Kafshët hanë sanë në dimër.',
    en: 'The animals eat __ in winter.',
    focus: 'sanë',
    retrievalEn: 'The animals eat hay in winter.',
    distractorIds: ['kashte', 'bar', 'ushqim'],
    retrievalDistractorIds: ['kashte', 'bar', 'ushqim'],
    cueTokens: ['Kafshët', 'hanë'],
    rationale: 'The verb hanë identifies sanë as animal feed rather than bedding straw.',
  }),
  flutur: reviewed({
    al: 'Një flutur ulet mbi një lule.',
    en: 'A __ lands on a flower.',
    focus: 'flutur',
    retrievalEn: 'A butterfly lands on a flower.',
    distractorIds: ['zog', 'shqiponje', 'ujk'],
    retrievalDistractorIds: ['zog', 'shqiponje', 'ujk'],
    cueTokens: ['ulet', 'lule'],
    rationale: 'Landing on a flower provides a natural visual situation without defining flutur through a cognate verb.',
  }),
  krah: reviewed({
    al: 'Zogu ka vetëm një krah.',
    en: 'The bird has only one __.',
    focus: 'krah',
    retrievalEn: 'The bird has only one wing.',
    distractorIds: ['krah_arm', 'dore', 'kembe'],
    retrievalDistractorIds: ['dore', 'kembe', 'sqep'],
    contrastIds: ['krah_arm'],
    cueTokens: ['Zogu'],
    rationale: 'Zogu makes the anatomical sense “wing” the only intended reading.',
    contrastRationales: { krah_arm: 'A bird in this simple anatomical description has a wing, not a human arm or shoulder.' },
  }),
  krah_arm: reviewed({
    al: 'Kam një plagë në krah.',
    en: 'I have a wound on my __.',
    focus: 'krah',
    retrievalEn: 'I have a wound on my arm.',
    distractorIds: ['krah', 'dore', 'kembe'],
    retrievalDistractorIds: ['dore', 'kembe', 'koke'],
    contrastIds: ['krah'],
    cueTokens: ['Kam', 'plagë'],
    rationale: 'The first-person injury frame selects the body-part sense used for an arm.',
    contrastRationales: { krah: 'The speaker is a person describing an injury, not a bird describing a wing.' },
    distractorLabels: { al2en: { krah_arm: 'arm' } },
  }),
  po_yes: reviewed({
    al: '— A je mirë? — Po.',
    en: '— Are you well? — __.',
    focus: 'po',
    retrievalEn: '— Are you well? — Yes.',
    distractorIds: ['po_prog', 'po_but', 'po_turn'],
    retrievalDistractorIds: ['jo', 'ndoshta', 'di'],
    contrastIds: ['po_prog', 'po_but', 'po_turn'],
    cueTokens: ['A', 'mirë'],
    rationale: 'As the complete reply to a yes/no question, po confirms the answer.',
    contrastRationales: {
      po_prog: 'No following verb is present for a progressive marker.',
      po_but: 'There is no second clause for an adversative conjunction to introduce.',
      po_turn: 'There is no pronoun or topic after po to receive a redirected question.',
    },
    audio: true,
  }),
  po_prog: reviewed({
    al: 'Po bie shi.',
    en: 'It __ raining.',
    focus: 'po',
    retrievalEn: 'It is raining.',
    distractorIds: ['po_yes', 'po_but', 'po_turn'],
    retrievalDistractorIds: ['nuk', 'a_q', 'do_fut'],
    defensibleAlternativeRationales: { en2al: {
      ende: '“Ende bie shi” is a grammatical, more specific statement that still entails the broad cue “It is raining”.',
      akoma: '“Akoma bie shi” is a grammatical, more specific statement that still entails the broad cue “It is raining”.',
    } },
    contrastIds: ['po_yes', 'po_but', 'po_turn'],
    cueTokens: ['bie', 'shi'],
    rationale: 'Directly before the weather verb bie, po marks an action happening now.',
    contrastRationales: {
      po_yes: 'Po is not a standalone reply to a question.',
      po_but: 'It precedes one verb phrase rather than joining contrasting clauses.',
      po_turn: 'It does not redirect a question to another person or topic.',
    },
  }),
  po_but: reviewed({
    al: 'Dua të vij, po nuk mundem.',
    en: 'I want to come, __ I cannot.',
    focus: 'po',
    retrievalEn: 'I want to come, but I cannot.',
    distractorIds: ['po_yes', 'po_prog', 'po_turn'],
    retrievalDistractorIds: ['sepse', 'prandaj', 'ose'],
    defensibleAlternativeRationales: { en2al: {
      por: 'Por is the standard conjunction for the same contrast and completes this sentence with the same meaning.',
    } },
    contrastIds: ['po_yes', 'po_prog', 'po_turn'],
    cueTokens: ['Dua', 'nuk'],
    rationale: 'The wish to come and the inability to do so form the contrast introduced by po.',
    contrastRationales: {
      po_yes: 'Po is embedded between clauses, not answering a polar question.',
      po_prog: 'A comma and complete following clause rule out the preverbal progressive marker.',
      po_turn: 'The second clause states a contrast instead of returning a question.',
    },
  }),
  po_turn: reviewed({
    al: 'Unë jam mirë, po ti?',
    en: 'I am well; __ you?',
    focus: 'po',
    retrievalEn: 'I am well; what about you?',
    distractorIds: ['po_yes', 'po_prog', 'po_but'],
    // “Dhe ti?” is also natural here (“And you?”), so conjunctions are not
    // valid wrong answers in this exact frame. Use continuators that leave the
    // displayed question grammatically incomplete instead.
    retrievalDistractorIds: ['sepse', 'kur', 'ku'],
    defensibleAlternativeRationales: { en2al: {
      dhe: '“Dhe ti?” naturally returns the same question as “Po ti?”.',
      edhe: 'Edhe can redirect the turn in closely related conversational frames and is not an unequivocal false answer.',
      por: '“Por ti?” can contrast and redirect attention to the other speaker in this short exchange.',
    } },
    contrastIds: ['po_yes', 'po_prog', 'po_but'],
    cueTokens: ['mirë', 'ti'],
    rationale: 'Following one person’s answer and preceding ti?, po returns the same question to the other speaker.',
    contrastRationales: {
      po_yes: 'Po is not the whole answer; ti follows it as the redirected topic.',
      po_prog: 'No action verb follows po.',
      po_but: 'The short pronoun question redirects the turn rather than asserting a contrasting clause.',
    },
  }),
  a_q: reviewed({
    al: 'A vjen çdo ditë?',
    en: '“Do you come every day?” begins with the Albanian __.',
    focus: 'a',
    retrievalEn: 'Do you come every day?',
    distractorIds: ['qe', 'se', 'nese'],
    retrievalDistractorIds: ['kur', 'pse', 'si'],
    cueTokens: ['vjen', 'ditë'],
    rationale: 'At the start of a complete polar question, a marks the clause as yes/no.',
  }),
  e_art: reviewed({
    al: 'Ura është e vjetër.',
    en: 'The bridge is old; Albanian uses the __ before this adjective.',
    focus: 'e',
    retrievalEn: 'The bridge is old.',
    distractorIds: ['e_link', 'e_obj', 'e_conj'],
    retrievalDistractorIds: ['i_art', 'shume', 'me_more'],
    contrastIds: ['e_link', 'e_obj', 'e_conj'],
    cueTokens: ['Ura', 'vjetër'],
    rationale: 'The feminine subject ura and following adjective vjetër select the feminine adjective article e.',
    contrastRationales: {
      e_link: 'Vjetër is an adjective here, not a genitive possessor.',
      e_obj: 'There is no transitive verb for e to serve as its object.',
      e_conj: 'E does not sit between two coordinated names or phrases.',
    },
  }),
  e_link: reviewed({
    al: 'Kjo është dera e shtëpisë.',
    en: 'This is the door __ the house.',
    focus: 'e',
    retrievalEn: 'This is the door of the house.',
    distractorIds: ['e_art', 'e_obj', 'e_conj'],
    retrievalDistractorIds: ['i_link', 'te_link', 'per'],
    contrastIds: ['e_art', 'e_obj', 'e_conj'],
    cueTokens: ['dera', 'shtëpisë'],
    rationale: 'Between feminine dera and genitive shtëpisë, e links the possessed noun to its owner.',
    contrastRationales: {
      e_art: 'Shtëpisë is a genitive noun, not an adjective describing dera.',
      e_obj: 'There is no verb for an object clitic to attach to.',
      e_conj: 'The nouns form a possessive phrase, not two coordinated items.',
    },
  }),
  e_obj: reviewed({
    al: 'Vajza pret bukën; plaku e sjell.',
    en: 'The girl waits for the bread; the old man brings __.',
    focus: 'e',
    retrievalEn: 'The girl waits for the bread; the old man brings it.',
    distractorIds: ['e_art', 'e_link', 'e_conj'],
    retrievalDistractorIds: ['i_obj', 'me_obj', 'te_obj'],
    defensibleAlternativeRationales: { en2al: {
      ta: 'Ta still carries the object “it” while adding an unstated second-person recipient.',
      ma: 'Ma still carries the object “it” while adding a first-person recipient not ruled out by the broad cue.',
      ua: 'Ua still carries the object “it” while adding a plural recipient not ruled out by the broad cue.',
    } },
    contrastIds: ['e_art', 'e_link', 'e_conj'],
    cueTokens: ['bukën', 'sjell'],
    rationale: 'The previously named bread supplies the referent that e replaces as the object of sjell.',
    contrastRationales: {
      e_art: 'E precedes a finite verb, not an adjective.',
      e_link: 'It attaches to a verb rather than linking a possessive noun phrase.',
      e_conj: 'It does not join two equal words or clauses.',
    },
    distractorLabels: { al2en: { e_obj: 'unstressed object pronoun: it' } },
  }),
  i_obj: reviewed({
    al: 'Djali pret; plaku i sjell ujë.',
    en: 'The boy waits; the old man brings __ water.',
    focus: 'i',
    retrievalEn: 'The boy waits; the old man brings him water.',
    distractorIds: ['i_art', 'i_link', 'e_obj'],
    retrievalDistractorIds: ['me_obj', 'te_obj', 'na'],
    contrastIds: ['i_art', 'i_link'],
    cueTokens: ['Djali', 'sjell'],
    rationale: 'The waiting boy is the recipient represented by i before the verb sjell.',
    contrastRationales: {
      i_art: 'I precedes a finite verb, not an adjective.',
      i_link: 'It is attached to a verb rather than linking a genitive noun phrase.',
    },
  }),
  e_conj: reviewed({
    al: 'Mujo e Halili ecin bashkë.',
    en: 'Mujo __ Halili walk together.',
    focus: 'e',
    retrievalEn: 'Mujo and Halili walk together.',
    distractorIds: ['e_art', 'e_link', 'e_obj'],
    retrievalDistractorIds: ['me', 'ose', 'pa'],
    defensibleAlternativeRationales: {
      al2en: { dhe: 'Dhe also means “and”, so it is not a false meaning for the marked folk coordinator.' },
      en2al: { dhe: 'Dhe is the standard Albanian coordinator and gives this line the same basic meaning.' },
    },
    contrastIds: ['e_art', 'e_link', 'e_obj'],
    cueTokens: ['Mujo', 'Halili', 'bashkë'],
    rationale: 'Between two epic names with a plural verb, e coordinates the pair in folk register.',
    contrastRationales: {
      e_art: 'Halili is a name, not an adjective.',
      e_link: 'The plural verb and bashkë show coordination rather than possession.',
      e_obj: 'No verb immediately follows e for it to be an object clitic.',
    },
    register: 'epic-folk',
  }),
  do: reviewed({
    al: 'Gjarpri do ujë.',
    en: 'The serpent __ water.',
    focus: 'do',
    retrievalEn: 'The serpent wants water.',
    distractorIds: ['do_fut', 'duhet', 'mund'],
    retrievalDistractorIds: ['kerko', 'pi', 'ka'],
    contrastIds: ['do_fut'],
    cueTokens: ['Gjarpri', 'ujë'],
    rationale: 'Do is followed directly by the wanted thing, not by të and a verb.',
    contrastRationales: { do_fut: 'The following word is the noun ujë, so do cannot begin a future verb phrase.' },
  }),
  do_fut: reviewed({
    al: 'Bolla do të bëhet kulshedër.',
    en: 'The Bolla __ become a kulshedra.',
    focus: 'do',
    retrievalEn: 'The Bolla will become a kulshedra.',
    distractorIds: ['do', 'duhet', 'mund'],
    retrievalDistractorIds: ['mund', 'duhet', 'sapo'],
    contrastIds: ['do'],
    cueTokens: ['të', 'bëhet'],
    rationale: 'The sequence do të plus verb bëhet is the standard future construction.',
    contrastRationales: { do: 'The lexical verb “wants” would take an object or a fuller complement, while this fixed chain marks future time.' },
  }),
  luan: reviewed({
    al: 'Fëmija luan pranë urës.',
    en: 'The child __ near the bridge.',
    focus: 'luan',
    retrievalEn: 'The child plays near the bridge.',
    distractorIds: ['luan_noun', 'punon', 'fle'],
    retrievalDistractorIds: ['punon', 'fle', 'qesh'],
    contrastIds: ['luan_noun'],
    cueTokens: ['Fëmija', 'pranë'],
    rationale: 'After the subject fëmija, luan fills the finite-verb position and describes an activity.',
    contrastRationales: { luan_noun: 'The indefinite article një is absent and the sentence already has fëmija as its subject.' },
  }),
  luan_noun: reviewed({
    al: 'Një luan ruan derën.',
    en: 'A __ guards the door.',
    focus: 'luan',
    retrievalEn: 'A lion guards the door.',
    distractorIds: ['luan', 'ujk', 'tiger'],
    retrievalDistractorIds: ['ujk', 'tiger', 'qen'],
    contrastIds: ['luan'],
    cueTokens: ['Një', 'ruan'],
    rationale: 'The article një and following verb ruan place luan in the subject noun slot.',
    contrastRationales: { luan: 'The sentence needs a noun after një; the verb “plays” cannot occupy that slot.' },
  }),
  ere: reviewed({
    al: 'Po fryn një erë e fortë.',
    en: 'A strong __ is blowing.',
    focus: 'erë',
    retrievalEn: 'A strong wind is blowing.',
    distractorIds: ['ere_smell', 'shi', 'mjegull'],
    retrievalDistractorIds: ['shi', 'bore', 'mjegull'],
    contrastIds: ['ere_smell'],
    cueTokens: ['Fryn', 'fortë'],
    rationale: 'The weather verb fryn and adjective fortë select the wind sense.',
    contrastRationales: { ere_smell: 'A smell does not blow as the subject of this weather sentence.' },
  }),
  ere_smell: reviewed({
    al: 'Këtu vjen erë buke.',
    en: 'There is a __ of bread here.',
    focus: 'erë',
    retrievalEn: 'There is a smell of bread here.',
    distractorIds: ['ere', 'tym', 'ze'],
    retrievalDistractorIds: ['tym', 'ze', 'drite'],
    contrastIds: ['ere'],
    cueTokens: ['vjen', 'buke'],
    rationale: 'The genitive buke names the source of a smell in the idiomatic expression vjen erë.',
    contrastRationales: { ere: 'The line describes bread being sensed, not moving air or weather.' },
  }),
  para: reviewed({
    al: 'Kthehu para natës.',
    en: 'Come back __ night.',
    focus: 'para',
    retrievalEn: 'Come back before night.',
    distractorIds: ['para_money', 'pas', 'deri'],
    retrievalDistractorIds: ['pas', 'gjate', 'brenda'],
    contrastIds: ['para_money'],
    cueTokens: ['Kthehu', 'natës'],
    rationale: 'Before the time noun natës, para expresses an earlier deadline.',
    contrastRationales: { para_money: 'Natës is a time expression, not something counted or spent as money.' },
    distractorLabels: { al2en: { para: 'before' } },
  }),
  para_money: reviewed({
    al: 'Kam para për bukë.',
    en: 'I have __ for bread.',
    focus: 'para',
    retrievalEn: 'I have money for bread.',
    distractorIds: ['para', 'lek', 'flori'],
    retrievalDistractorIds: ['uje', 'kripe', 'kohe'],
    defensibleAlternativeRationales: { en2al: {
      lek: 'Having lek for bread is a natural, more concrete way to say that the speaker has money for bread.',
    } },
    contrastIds: ['para'],
    cueTokens: ['Kam', 'bukë'],
    rationale: 'Having para to buy bread selects the everyday money sense.',
    contrastRationales: { para: 'The possessive verb kam and purpose phrase për bukë do not describe spatial or temporal “before”.' },
  }),
  me_more: reviewed({
    al: 'Ky mal është më i lartë se tjetri.',
    en: 'This mountain is __ elevated than the other one.',
    focus: 'më',
    retrievalEn: 'This mountain is higher than the other one.',
    distractorIds: ['me_obj', 'shume', 'pak'],
    retrievalDistractorIds: ['shume', 'vertete', 'pak'],
    contrastIds: ['me_obj'],
    cueTokens: ['i', 'lartë'],
    rationale: 'Before the articulated adjective i lartë, më forms the comparative “higher”.',
    contrastRationales: { me_obj: 'There is no verb assigning an object role to “me”; më modifies the following adjective.' },
  }),
  dhe_gave: reviewed({
    al: 'Ti më dhe bukën.',
    en: 'You __ me the bread.',
    focus: 'dhe',
    retrievalEn: 'You gave me the bread.',
    distractorIds: ['dhe', 'jep', 'sjell'],
    retrievalDistractorIds: ['jep', 'sjell', 'merr'],
    contrastIds: ['dhe'],
    cueTokens: ['Ti', 'më', 'bukën'],
    rationale: 'Between a subject and two objects, dhe fills the past-tense verb slot meaning “gave”.',
    contrastRationales: { dhe: 'The line needs a finite verb; a conjunction cannot connect ti to an object-clitic phrase.' },
  }),
  me_obj: reviewed({
    al: 'Plaku më jep bukë.',
    en: 'The old man gives __ bread.',
    focus: 'më',
    retrievalEn: 'The old man gives me bread.',
    distractorIds: ['me_more', 'te_obj', 'e_obj'],
    retrievalDistractorIds: ['te_obj', 'na', 'e_obj'],
    contrastIds: ['me_more'],
    cueTokens: ['Plaku', 'jep'],
    rationale: 'Immediately before jep, më identifies the recipient “me”.',
    contrastRationales: { me_more: 'Më modifies the verb as its object, not an adjective as a comparative marker.' },
  }),

  // High-frequency function words also require a lived context even when no
  // other dictionary entry happens to share their spelling.
  nuk: reviewed({
    al: 'Nuk kam ujë.',
    en: 'I do __ have water.',
    focus: 'nuk',
    retrievalEn: 'I do not have water.',
    distractorIds: ['mos', 'po_prog', 'do_fut'],
    retrievalDistractorIds: ['po_prog', 'sapo', 'akoma'],
    cueTokens: ['kam', 'ujë'],
    rationale: 'Before the finite verb kam, nuk negates the statement.',
  }),
  mos: reviewed({
    al: 'Mos e hap derën.',
    en: '__ open the door.',
    focus: 'mos',
    retrievalEn: 'Do not open the door.',
    distractorIds: ['nuk', 'duhet', 'mund'],
    retrievalDistractorIds: ['nuk', 'sapo', 'perseri'],
    cueTokens: ['hap', 'derën'],
    rationale: 'Sentence-initial mos before an action gives a negative command.',
  }),
  edhe: reviewed({
    al: 'Merr edhe ujë.',
    en: 'Take water __.',
    focus: 'edhe',
    retrievalEn: 'Take water too.',
    distractorIds: ['dhe', 'ose', 'por'],
    retrievalDistractorIds: ['pak', 'shume', 'perseri'],
    cueTokens: ['Merr', 'ujë'],
    rationale: 'After an implied earlier item, edhe adds water as one more thing to take.',
  }),
  por: reviewed({
    al: 'Është vonë, por ura është ende hapur.',
    en: 'It is late, __ the bridge is still open.',
    focus: 'por',
    retrievalEn: 'It is late, but the bridge is still open.',
    distractorIds: ['po_but', 'dhe', 'ndersa'],
    retrievalDistractorIds: ['sepse', 'prandaj', 'ose'],
    defensibleAlternativeRationales: { en2al: {
      ndersa: 'Ndërsa can introduce the same contrast between lateness and the bridge remaining open.',
    } },
    cueTokens: ['vonë', 'hapur'],
    rationale: 'The late hour and still-open bridge are contrasting facts joined by por.',
  }),
  apo: reviewed({
    al: 'Do kafe apo çaj?',
    en: 'Do you want coffee __ tea?',
    focus: 'apo',
    retrievalEn: 'Do you want coffee or tea?',
    distractorIds: ['ose', 'dhe', 'por'],
    retrievalDistractorIds: ['dhe', 'me', 'pa'],
    defensibleAlternativeRationales: { en2al: {
      ose: 'Ose is also used for alternatives and can be heard in questions, even though apo is preferred here.',
    } },
    cueTokens: ['kafe', 'çaj'],
    rationale: 'In a direct question offering two drinks, apo marks the choice between them.',
  }),
  ose: reviewed({
    al: 'Mund të presim këtu ose te ura.',
    en: 'We can wait here __ at the bridge.',
    focus: 'ose',
    retrievalEn: 'We can wait here or at the bridge.',
    distractorIds: ['apo', 'dhe', 'por'],
    retrievalDistractorIds: ['dhe', 'jo', 'por'],
    defensibleAlternativeRationales: { en2al: {
      apo: 'Apo can also coordinate alternatives in conversational Albanian, so it is not unequivocally impossible here.',
    } },
    cueTokens: ['këtu', 'ura'],
    rationale: 'In a statement naming two possible meeting places, ose presents alternatives.',
  }),
  se: reviewed({
    al: 'E di se ai është këtu.',
    en: 'I know __ he is here.',
    focus: 'se',
    retrievalEn: 'I know that he is here.',
    distractorIds: ['sepse', 'nese', 'kur'],
    retrievalDistractorIds: ['sepse', 'nese', 'kur'],
    defensibleAlternativeRationales: {
      al2en: { qe: 'Që can introduce the same reported content and its broad function label overlaps this answer.' },
      en2al: { qe: '“E di që ai është këtu” is a standard sentence with the same meaning.' },
    },
    cueTokens: ['di', 'ai'],
    rationale: 'After di, se introduces the content of what the speaker knows.',
  }),
  qe: reviewed({
    al: 'Ky është burri që punon në mulli.',
    en: 'This is the man __ works at the mill.',
    focus: 'që',
    retrievalEn: 'This is the man who works at the mill.',
    distractorIds: ['se', 'ku', 'kur'],
    retrievalDistractorIds: ['se', 'ku', 'kur'],
    cueTokens: ['burri', 'punon'],
    rationale: 'After burri, që introduces the relative clause that identifies which man.',
  }),
  ndersa: reviewed({
    al: 'Unë mbaj bukën, ndërsa ti mban ujin.',
    en: 'I carry the bread, __ you carry the water.',
    focus: 'ndërsa',
    retrievalEn: 'I carry the bread, while you carry the water.',
    distractorIds: ['sepse', 'prandaj', 'ose'],
    retrievalDistractorIds: ['sepse', 'prandaj', 'ose'],
    distractorLabels: { al2en: { ndersa: 'while (contrasting two parallel clauses)' } },
    defensibleAlternativeRationales: {
      al2en: {
        por: 'Por can express a compatible contrast between the two parallel clauses.',
        dhe: 'Dhe can truthfully coordinate the two simultaneous actions without contradicting the displayed situation.',
      },
      en2al: {
        por: 'Por produces a grammatical compatible contrast rather than an unequivocally false sentence.',
        dhe: 'Dhe produces a grammatical coordination that preserves both facts in the cue.',
      },
    },
    cueTokens: ['Unë', 'ti'],
    rationale: 'The two simultaneous subjects and parallel actions are contrasted by ndërsa.',
  }),
  me: reviewed({
    al: 'Pi çaj me mjaltë.',
    en: 'Drink tea __ honey.',
    focus: 'me',
    retrievalEn: 'Drink tea with honey.',
    distractorIds: ['pa', 'dhe', 'ose'],
    retrievalDistractorIds: ['pa', 'dhe', 'ose'],
    cueTokens: ['çaj', 'mjaltë'],
    rationale: 'Between a drink and an ingredient, me marks what accompanies the tea.',
  }),
  ne: reviewed({
    al: 'E gjeta në rrugë.',
    en: 'I found it __ the road.',
    focus: 'në',
    retrievalEn: 'I found it on the road.',
    distractorIds: ['tek', 'nga', 'prane'],
    retrievalDistractorIds: ['nen', 'prane', 'pas'],
    defensibleAlternativeRationales: { en2al: {
      mbi: 'Mbi rrugë can also describe being on the road, so the broad English preposition does not rule it out safely.',
    } },
    cueTokens: ['gjeta', 'rrugë'],
    rationale: 'With the place noun rrugë, në locates where the object was found.',
    distractorLabels: { al2en: { ne: 'marks location here: on' } },
  }),
  tek: reviewed({
    al: 'Po të pres tek ura.',
    en: 'I am waiting for you __ the bridge.',
    focus: 'tek',
    retrievalEn: 'I am waiting for you at the bridge.',
    distractorIds: ['ne', 'nga', 'prane'],
    retrievalDistractorIds: ['ne', 'prane', 'pas'],
    cueTokens: ['pres', 'ura'],
    rationale: 'Tek points to the bridge as the specific meeting place.',
  }),
  nga: reviewed({
    al: 'Po vij nga fshati.',
    en: 'I am coming __ the village.',
    focus: 'nga',
    retrievalEn: 'I am coming from the village.',
    distractorIds: ['ne', 'tek', 'per'],
    retrievalDistractorIds: ['ne', 'tek', 'prej'],
    cueTokens: ['vij', 'fshati'],
    rationale: 'With the motion verb vij, nga marks the place the movement starts from.',
  }),
  per: reviewed({
    al: 'Kjo bukë është për ty.',
    en: 'This bread is __ you.',
    focus: 'për',
    retrievalEn: 'This bread is for you.',
    distractorIds: ['me', 'pa', 'nga'],
    retrievalDistractorIds: ['me', 'pa', 'nga'],
    cueTokens: ['bukë', 'ty'],
    rationale: 'Between the offered bread and its recipient ty, për marks who it is intended for.',
    distractorLabels: { al2en: { per: 'marks the intended recipient: for' } },
  }),
  pa: reviewed({
    al: 'Pi kafe pa qumësht.',
    en: 'Drink coffee __ milk.',
    focus: 'pa',
    retrievalEn: 'Drink coffee without milk.',
    distractorIds: ['me', 'dhe', 'ose'],
    retrievalDistractorIds: ['me', 'dhe', 'ose'],
    cueTokens: ['kafe', 'qumësht'],
    rationale: 'Between a drink and an omitted ingredient, pa marks absence: without milk.',
  }),
})
