// EXPLICIT map placement — one physical spot, ONE coordinate.
// Each entry is either
//   id: [x, y]       the node stands at its OWN spot (most nodes), or
//   id: 'anchorId'   the node stands AT that node's spot — the story
//                    continues at the same physical place.
// Move a place by editing its single [x, y]: everyone standing there moves
// with it. If the character moves even slightly, the node gets its OWN
// coordinate — never reuse another spot's numbers (mapaudit flags collisions).
export const NODE_AT = {
  // the traveller's camp on the WEST bank, before the old stone bridge of the
  // tanners (Ura e Tabakëve) — the bridge you cross from here IS that bridge
  start: [92, 598],
  bisedaUra1: 'start',
  bisedaUra2: 'start',
  bisedaUra3: 'start',
  bisedaUraPlan: 'start',
  bisedaShesh: 'start',
  bisedaKroi: 'start',
  lendina: [-430, 452],
  plaka: [576, 388],
  agaYmer1: 'plaka',
  syriKeq1: [404, 496],
  syriKeqFund: 'syriKeq1',
  breshka1: [348, 614],
  breshkaMire: 'breshka1',
  breshkaFund: 'breshka1',
  agaYmer2: 'plaka',
  agaYmerStay: 'plaka',
  agaYmerFund: 'plaka',
  pylli1: [-560, 400],
  // Prespa is its own lakeside woodland, not the great forest beside the
  // opening bridge. The tale's two conclusions happen at that same place.
  prespaPyll: [-40, 1510],
  prespaLiri: 'prespaPyll',
  prespaFund: [20, 1680], // after the flood, the town itself has become the lake
  // Argjiro's Gjirokaster fortress is a distinct tale-place. It must not share
  // Baba Tomor's summit merely because the player first sees it from there.
  argjiroKala: [540, 1450],
  argjiroFund: 'argjiroKala',
  argjiroRob: 'argjiroKala',
  // Ali Pasha's last stand is on Ioannina's lake island, a named inland place;
  // it must not be collapsed onto the Adriatic coast where the tale is entered.
  aliPashaLiqen: [220, 1720],
  aliPashaVdes: 'aliPashaLiqen',
  aliPashaRob: 'aliPashaLiqen',
  binoshetLumi: 'lumi',
  binoshetFund: 'lumi',
  binoshetHije: 'lumi',
  // The twins' later road is a sequence of distinct source places. The ending
  // returns to Bardhakuqja's river city after the recovered kingdom journey.
  binoshetKasollja: [-500, 700],
  binoshetKopshtiZanave: [-250, -700],
  binoshetGardhiHanda: [-40, -520],
  binoshetGardhiZjerma: 'binoshetGardhiHanda',
  binoshetZambak: 'binoshetGardhiHanda',
  binoshetDasma: 'binoshetGardhiHanda',
  binoshetKuvendi: 'binoshetGardhiHanda',
  binoshetKurora: [560, 1260],
  binoshetLuftaFillon: 'binoshetKurora',
  binoshetLuftaZgjat: 'binoshetKurora',
  binoshetLuftaFund: 'binoshetKurora',
  binoshetShpata: 'binoshetKurora',
  binoshetNata: 'binoshetKurora',
  binoshetZjarri: 'lumi',
  binoshetTeNena: 'binoshetKurora',
  binoshetDyKurorat: 'lumi',
  odaJutbina: [590, -282], // the men's room of the great kulla — the border-news oda
  // Jutbina is a HAMLET, not one twenty-scene room. Its tales occupy the oda,
  // mejdan, wounded hero's trees, Krajl's prison, horse-guard and Ali's house.
  haliliDeka: 'odaJutbina',
  haliliMejdan: 'mejdan1',
  haliliJeton: 'odaJutbina',
  gbMuji1: [720, -500],
  gbMujiFund: 'gbMuji1',
  gbMujiVdes: 'gbMuji1',
  osmaniBurg: [810, -310],
  osmaniVdekur: 'osmaniBurg',
  osmaniProvat: 'osmaniBurg',
  osmaniVallja: 'osmaniBurg',
  osmaniShpata: 'osmaniBurg',
  osmaniZbuluar: 'osmaniBurg',
  // The escape ends on the homeward approach to Jutbina. It cannot alias the
  // hamlet hub: the preceding choice is made at the distant Krajl's prison,
  // and treating the ending as the exact same card as an unlinked hub made a
  // false instantaneous co-location on the map.
  osmaniLiri: [520, -320],
  osmaniRob: 'osmaniBurg',
  // Two distinct Krajl songs use two distinct foreign prisons. Halili is
  // woken at his own Jutbina doorway, rides east across the frontier, and
  // brings Mujo back to the hamlet by a separate homeward approach.
  kreshnikRrembimi1: [650, -280],
  kreshnikRrembimiBurg: [930, -300],
  kreshnikRrembimiFund: [555, -315],
  kreshnikRrembimiHumbur: 'kreshnikRrembimiFund',
  kreshnikRrembimiRefuz: 'kreshnikRrembimi1',
  // Mujo and Behuri: the muster is inside the great oda, then the company
  // crosses an authored chain of high pasture, spring, enemy kulla and open
  // mejdan. The finale reaches the Jutbina road again; none of these foreign
  // sites aliases another Krajl tale's tower.
  behuriJutbina: 'odaJutbina',
  behuriNdarja: [720, -590],
  behuriBurimi: [840, -610],
  behuriKulla: [950, -520],
  behuriMejdan: [900, -400],
  behuriFund: [700, -350],
  behuriKotorHumbur: 'behuriNdarja',
  behuriBurimHumbur: 'behuriBurimi',
  behuriKullaHumbur: 'behuriKulla',
  behuriMejdanHumbur: 'behuriMejdan',
  halilGarria1: [820, -220],
  halilGarriaFund: 'jutbina',
  halilGarriaKeq: 'halilGarria1',
  mujoKale: [780, -410],
  mujoKaleFund: 'mujoKale',
  mujoKaleLarg: 'mujoKale',
  aliBajr1: [760, -120],
  aliBajrFund: 'aliBajr1',
  aliBajrKeq: 'aliBajr1',
  pylliThelle: [-700, 480],
  shokuUjk: 'pylliThelle',
  udha: [-560, 720],
  stihi1: [-560, 560],
  stihiDjeg: 'stihi1',
  stihiFund: 'stihi1',
  // ── Jutbina — the kreshnik hamlet on its highland shelf: each tale has its
  // own kulla / spot around the hamlet centre; the zanas' meadow lies above,
  // the mejdan duelling ground below, the lament-house at the west edge.
  vajtim1: [478, -390],
  mujoHak1: [300, -320],
  mujoHakFund: 'mujoHak1',
  mujoHakKeq: 'mujoHak1',
  mejdan1: [470, -260],
  mejdan2: 'mejdan1',
  mejdanKeq: 'mejdan1',
  besaVella: 'mejdan1',
  besaThyer: 'mejdan1',
  vajtimFund: 'vajtim1',
  lumi: [200, 820],
  veraDite1: [458, 484],
  veraDiteFund: 'veraDite1',
  flocka1: [140, 1560],
  flockaFund: 'flocka1',
  deti1: [1010, 800],
  kripore1: [902, 912], // the salt pans — anchored on the drawn kripore art (DebugView)
  punaKripe: 'kripore1',
  detiThelle1: [1360, 1200],
  detiThelle2: [1680, 1420],
  detiNuse: 'detiThelle2',
  detiStuhi: 'detiThelle1',
  zana1: [300, 960],
  zanaQumesht: [260, 1140],
  zanaKripe: 'zanaQumesht',
  rrethi: [300, 1150],
  mali1: [180, -430],
  cajMali1: 'mali1',
  mali2: [140, -500],
  mali3: [110, -560],
  tomor1: [470, -720],
  tomor2: 'tomor1',
  pusi: [420, 1960],
  bota1: [380, 2070],
  bota2: [200, 2320],
  porta1: [470, 2210],
  portaVdes: 'porta1',
  bukura1: [640, 2120],
  bukura2: 'bukura1',
  kulshedra1: [620, 2340],
  fitorja: 'kulshedra1',
  pusi2: [1560, 1640],
  shqiponja1: 'pusi2',
  siperfaqja: [1180, 1540],
  kalaMur: [300, 1360],
  kalaMjegull: 'kalaMur',
  kalaPlak: 'kalaMur',
  kalaNgjitje: 'kalaMur',
  kalaLutje: 'kalaMur',
  kalaFundBesa: 'kalaMur',
  kalaFundTurp: 'kalaMur',
  shtepia: [360, 480],
  dranguasi: 'kulshedra1',
  mishiVetes: 'pusi2',
  fshehur: [95, 900],
  thesarOra: [120, 950],
  // At the fork below, the entrance is the RIGHT-hand return and botaHumbur is
  // the LEFT-hand road. Keep their x positions faithful to those words.
  shpellaHyrje: [400, 1290],
  shpellaRruget: [235, 1430],
  qyteti: [300, 2060],
  // ── living Gjakova stays on the surface, outside the cavern. The dead city
  // below has only qyteti + thesar2 and no living inhabitants.
  qytetiUdhetar: [10, 930],
  sheshi: [15, 1020],
  lemoshaFund: 'sheshi',
  lemoshaBuke: 'sheshi', // the bread-alms beat — the same doorway on the square
  tregtari: [80, 980],
  blerjaBuke: 'tregtari',
  blerjaKripe: 'tregtari',
  shitjaCaj: 'tregtari',
  tregtari2: [90, 1025], // the trader's dyqan — its own doorway beside the stall
  blerjaLahuta: 'tregtari2',
  plisiFund: 'tregtari2',
  xhubletaFund: 'tregtari2',
  bujtina: [50, 1065],
  gjumiBujtina: 'bujtina',
  kafeja1: 'bujtina',
  kafejaFund: 'bujtina',
  fallFund: 'bujtina',
  gezuarFund: 'bujtina',
  sheruesi: [-30, 1050],
  kopshtiBar: [-70, 1090], // the healer's herb garden behind the house
  sherimiBar: 'sheruesi',
  besimeFund: 'sheruesi',
  udhetariHuaj: [-30, 990],
  kurbetiFund: 'udhetariHuaj',
  udhaShenja: [20, 1105],
  udhaUdhetari: 'udhaShenja', // the traveller's leaving — the same old door as an event
  // ── the sea-road beyond the old door: the toll-road's first stretch, then the
  // waystone where it bends down toward the far coast (the traveller's parting)
  rrugaDetit: [145, 1150],
  guriUdhes: [250, 1190],
  lamtumira: 'guriUdhes', // the farewell at the waystone — same spot as the standing stone
  thesar2: [430, 2210],
  thesarKthyer: [500, 2250],
  gjarperVrare: 'thesar2',
  gjarperNgrene: 'thesar2',
  djegur: [710, 2280],
  rene: 'pusi2',
  detiUp: 'detiThelle2',
  detiNgrene: 'detiThelle2',
  humbur: [560, 2340],
  oraBardhe: 'humbur',
  oraZeze: 'humbur',
  eaten: 'pylliThelle',
  pylliLoop: [-440, 540],
  shtojzovalle1: [-460, 800],
  shtojzovalle2: 'shtojzovalle1',
  shtojzovalleVallja: 'shtojzovalle1',
  shtojzovalleLot: 'shtojzovalle1',
  shtojzovalleNuse: 'shtojzovalle1',
  shtojzovalleBekim: 'shtojzovalle1',
  shtrigaNate: 'lendina', // waiting "here" keeps the witch's transformation at the clearing fire
  besaFire: 'lendina',
  shtrigaIkur: 'shtrigaNate',
  gjumi: 'lendina', // the shared sleep scene is the clearing's sleeping-ground
  fshatiDil: [604, 180],
  dilFrike: 'fshatiDil',
  ura: [380, 1240],
  maja: [300, -820],
  jutbina: [540, -360],
  kengaJutbina: 'jutbina', // your lahuta song among the kullas — the hamlet centre
  mujiZana1: [505, -432],
  mujiZana2: 'mujiZana1',
  mujiFund: 'mujiZana1',
  mujiPasuri: 'mujiZana1',
  mujiDije: 'mujiZana1',
  tomor3: 'tomor1',
  dera: 'bota1',
  sprova: [140, 2130],
  gjarpri: 'bota2',
  uji: [180, 2360],
  kthimi: [560, 2080],
  // The last homeward vista reaches the dry edge of the coast road. From there
  // the path turns inland to the road and builders' house below Rozafa; this
  // scene must stand on the drawn shore, not out in the Adriatic.
  udhaKthimit: [180, 1210],
  ktheu3: [800, 1570],
  shqipe1: [120, 1320],
  shqipe2: [95, 1250],
  shqipe3: 'shqipe2',
  shqipeBarter: 'shqipe2',
  shqipeKapur: 'shqipe2',
  shqipeFund: 'shqipe2',
  // Sari Salltëk's story is heard at the well, but happens at its own cave near
  // Krujë. A narrated tale is not the same physical place as its storyteller.
  sari1: [640, -180],
  sari2: 'sari1',
  sariFund: 'sari1',
  gjarperBurr1: 'bota2',
  gjarperBurrVdes: 'bota2',
  gjarperBurr2: 'bota2',
  gjarperKerkim: 'bota2',
  gjarperOrigin: 'bota2',
  gjarperRefuz: [110, 2400],
  gjarperKulshedra: [1700, 1750],
  gjarperKulVdes: 'gjarperKulshedra',
  gjarperBurrFund: 'gjarperKulshedra',
  nastradin1: [404, 150],
  nastradinFund: 'nastradin1',
  kostandin1: [336, 256],
  kostandin2: 'kostandin1',
  kostandin3: 'kostandin1',
  kostandinFund: 'kostandin1',
  gjizar1: [672, 214],
  gjizar2: [720, 164],
  // Gjizar is an embodied journey, not seven pages heard without leaving the
  // back lane. The no-return road reaches the world below, the theft occurs
  // at the established Earthly Beauty's court, and the brothers' betrayal has
  // its own well on the long homeward road. Only the resolved ending returns
  // to the king's town where the tale began.
  gjizarUdha: [360, 2320],
  gjizarPallat: 'bukura1',
  gjizarKap: 'bukura1',
  gjizarTradheti: [800, 1940],
  gjizarPus: 'gjizarTradheti',
  gjizarFund: [755, 125],
  // Tomor & Shpirag embodied arc — Tomor's slopes share tomor1; Shpirag's ridge
  // (Berat at its foot) gets its OWN spot below the summit, fixing the old bug of
  // Berat resolving onto the sacred summit (maja).
  // The embodied giant's home/slope is below the pilgrimage shrine; the duel's
  // aftermath belongs at the Shpirag battlefield, not on Baba Tomor's summit.
  tsHyrje: [350, -600],
  tsNuse: 'tsHyrje',
  tsRoje: 'tsHyrje',
  tsZgjim: 'tsHyrje',
  tsShpeto: 'tsHyrje',
  tsFundTomor: 'shpirag1',
  shpirag1: [560, -360],
  tsRast: 'shpirag1',
  tsBeteje: 'shpirag1',
  shpiragFund: 'shpirag1',
  dhia1: [80, -520],
  dhiaFund: 'dhia1',
  tre1: [280, 2470],
  tre2: 'tre1',
  tre3: 'tre1',
  udhetimi1: [300, 2380],
  udhetimi2: [240, 2440],
  bukuraThellesi: 'bukura1',
  bregu: [780, 1080],
  // The shore-village scene already says the wounded hero, sister and kulla
  // are "here". Listening and sleeping in the following scenes do not travel.
  balozMotra: 'bregu',
  balozTribut: 'balozMotra',
  balozZgjedh: 'balozMotra',
  balozLufte: [880, 1130],
  balozKoke: [960, 1200],
  balozFitore: [640, 1100],
  bregFle: 'bregu',
  bregHumb: [1000, 1080],
  zanaProva: [410, 1040],
  zanaProva2: 'zanaProva',
  zanaGold: 'zanaQumesht',
  zanaDije: 'zanaQumesht',
  zanaFole: [80, 1000],
  foleShpetuar: 'zanaFole',
  tomorProva: [420, -640],
  tomorStuhi: 'tomorProva',
  ngjitja1: 'pusi2',
  ngjitja2: 'pusi2',
  ngjitja3: 'pusi2',
  fshatiSheshi: [499, 432],
  porosiaShesh: 'fshatiSheshi',
  pazariFshatit: 'fshatiSheshi',
  pazariPerserit: 'fshatiSheshi',
  porosiaBlerje: 'fshatiSheshi',
  dasma1: [598, 448], // the wedding yard — the feast-house ground east of the square (krushqit ride here)
  dasmaFund: 'dasma1',
  valleFund: 'dasma1',
  sheshiPlak: 'fshatiSheshi',
  sheshiPlak2: 'fshatiSheshi',
  sheshiPlak3: 'fshatiSheshi',
  pusiThate: [480, 444],
  pusiGuri: 'pusiThate',
  peri1: [180, -520],
  periFund: 'peri1',
  periKeq: 'peri1',
  // — Maro Përhitura: the njerka's house at the homes' edge; the night scenes
  //   share the mill spot (the tale's own setting) —
  maroShtepi: [252, 410],
  maroNjerka: 'maroShtepi',
  maroNisja: 'maroShtepi',
  maroMulli1: [186, 584], // the inner millstone floor during Maro's night vigil
  maroXhindet1: 'maroMulli1',
  maroLitani1: 'maroMulli1',
  maroLitani2: 'maroMulli1',
  maroLitani3: 'maroMulli1',
  maroShtremberDore: 'maroMulli1',
  maroNataHumbur: 'maroMulli1',
  maroDoraShtember: 'maroMulli1',
  maroDoraFalje: 'maroMulli1',
  maroShtrember: 'maroMulli1',
  maroLiloNis: 'maroShtepi',
  maroLiloKthim: 'maroShtepi',
  maroLajmi: 'maroShtepi',
  maroTetua: [934, 512],
  maroHani: [540, 84],
  maroIkja: [740, 340], // midnight flight on the road between the auntie's door and home
  maroMesnata: 'maroHani', // midnight strikes AT the han — the walk home is its exit edge
  maroKrushqit: [350, 330], // the wedding party surrounds the house from the road
  maroPrincesha: [850, 80], // the bridal road into the prince's country
  maroPallati: [1050, -40],
  maroGjilpera: 'maroPallati',
  maroLindja: 'maroPallati',
  maroZogu: 'maroPallati',
  // The bird flies from the palace window to the prince's garden wood. The
  // later tree/perching and restoration scenes happen there, not in the room.
  maroKopshti: [980, 100],
  maroFundi: 'maroKopshti',
  maroCiuCiu: 'maroKopshti',
  nenaDiell1: [516, 400],
  nenaDiellFund: 'nenaDiell1',
  karkanxholl1: [-720, 820],
  karkanxhollFund: 'karkanxholl1',
  karkanxhollKeq: 'karkanxholl1',
  dhelpra1: [-360, 600],
  dhelpra2: 'dhelpra1',
  dhelpraFund: 'dhelpra1',
  dhelpraKeq: 'dhelpra1',
  nastradinGjyq1: 'nastradin1',
  nastradinGjyqFund: 'nastradin1',
  nastradinGjyqKeq: 'nastradin1',
  rusha1: [610, -428],
  rushaFund: 'rusha1',
  rushaKeq: 'rusha1',
  arushe2: 'pylli1',
  pallatiZi: [768, 448],
  pallatRoje: 'pallatiZi',
  pallatRojeZi: 'pallatiZi',
  pallatRojePse: 'pallatiZi',
  libriDiell: [418, 392],
  sofraMikut: 'libriDiell',
  sofraMikut2: 'libriDiell',
  pallatiKthim: 'pallatiZi',
  // ── the Sun's house — a real explorable compound on its cloud-plateau:
  // house → garden (west wing) → golden oda (east wing) → the forecourt where
  // the beasts are summoned (south gate) → the road of the Sun down the ray,
  // with the sun-tree beside it (the escape, rrugaDielli2, ends by the village).
  diellShtepi1: [300, -1150],
  diellKopsht: [205, -1085],
  diellKopshtFol: 'diellKopsht',
  diellOda: [385, -1125],
  diellThirrKul: [300, -1062],
  diellKulVdes: 'diellThirrKul',
  rrugaDielli1: [300, -985],
  pemaDielli: [382, -1060],
  pemaVdes: 'pemaDielli',
  rrugaDielli2: [400, 120],
  kopshtMermer1: [690, 470],
  kopshtMermer2: 'kopshtMermer1',
  mermerZgjim: 'kopshtMermer1',
  mermerTradheti: 'kopshtMermer1',
  patatGruaja: 'kopshtMermer1',
  mbretiDrejtesi: 'kopshtMermer1',
  patatHesht: 'kopshtMermer1',
  mermerSli: 'kopshtMermer1',
  fshatiLanes: [878, 468],
  djepi1: [884, 542],
  djepi3: 'djepi1',
  djepiKeq: 'djepi1',
  djepi2: 'djepi1',
  djepiFund: 'djepi1',
  fshatiJeta: [322, 430],
  kafeneja: 'fshatiSheshi',
  kafeneja2: 'fshatiSheshi',
  kroiGrate: 'kroi1',
  kroiGrate2: 'kroi1',
  vatra: [300, 378],
  vatraGjarpri: 'vatra', // the serpent's saucer — at the hearth itself
  qilim: [288, 468],
  qilimNena: 'qilim', // the mother speaks at the loom — same spot as the qilim scene
  bariu: [300, 560],
  punaBariu: 'bariu',
  gjysmegjel1: [392, 566],
  gjysmegjel2: 'gjysmegjel1',
  gjysmegjelFund: 'gjysmegjel1',
  kulle1: [868, 392],
  kulle2: 'kulle1',
  kulleFal: 'kulle1',
  kulleGjak: 'kulle1',
  fshatiBesa: [430, 236],
  fshatiCaul: 'fshatiBesa',
  udheNate: 'udha',
  udheLugat: 'udha',
  udheOra: 'udha',
  kalaNate: 'udhaKthimit',
  kalaMengjes: 'udhaKthimit',
  kulshLufte1: 'kulshedra1',
  bijaHene1: [500, 2400],
  bijaHeneFund: [500, 2470],
  kulshLufte2: 'kulshedra1',
  springReturn: [670, 2260],
  bukuraKthim: [710, 2200],
  udhaThate: [-460, 640],
  maliHumbur: [500, -975],
  lumiHumbur: [230, 1075],
  botaHumbur: [100, 1890],
  ujkuUje: 'udhaThate',
  // The Blue Eye is reached by leaving the dry forest road for the river's
  // western headwater. This stays a real walk (<500 map units) while bringing
  // the spring inside the river country instead of drawing it in the woods.
  udhaSyri: [-85, 850],
  syriKanali: 'udhaSyri',
  syriFund: 'udhaSyri',
  uraFshaj: [310, 1120],
  maliStuhi: 'mali3',
  zbritjaThelle: [400, 2020],
  qeniGate: 'bota1',
  majaEagle: 'tomor1',
  tomorBekim: 'tomor1',
  tomorZbritje: [360, -160],
  ujiShpella: [330, 2290],
  ktheu1: [1120, 1680],
  ktheu2: [1220, 1830],
  nenaShtrige: 'ktheu2',
  bukuraLirim: 'bukura1',
  dordolec1: [554, 480],
  dordolec2: 'dordolec1',
  dordolecSyriFund: 'dordolec1',
  dordolecFund: [540, 430],
  bolla1: [330, 850],
  bolla2: 'bolla1',
  bollaFund: 'bolla1',
  katallan1: [-40, -360],
  katallanRob: 'katallan1',
  katallanGur: 'katallan1',
  katallanZjarr: 'katallan1',
  katallanVerbim: 'katallan1',
  katallanFund: 'katallan1',
  katallanVdes: 'katallan1',
  gjak1: 'fshatiDil',
  gjak2: 'fshatiDil',
  gjakFund: 'fshatiDil',
  zuku1: [668, -318],
  zuku2: 'zuku1',
  zukuFund: 'zuku1',
  // the sword-brothers tale marches west from the bear glade toward the palace:
  // the brothers -> the moat leap -> the road to the palace gate
  kordha1: [-600, 352],
  kordha2: [-680, 260],
  kordhaMoat: [-648, 306],
  kordhaMoatVdes: 'kordhaMoat',
  kordhaUdha: [-668, 282],
  // Beyond the moat and its road stands the king's palace. Its interior,
  // dragon ordeal, spring and conclusions share that destination; they are not
  // the brothers' earlier woodland stop.
  kordhaPallat: [-790, 150],
  kordhaZjarr: 'kordhaPallat',
  kordhaProva: 'kordhaPallat',
  kordhaProvaVdes: 'kordhaPallat',
  kordhaFund: 'kordhaPallat',
  kordhaDeti: 'kordhaPallat',
  shurdhi1: [60, -680],
  shurdhiFund: 'shurdhi1',
  kali1: 'mali3',
  kaliFund: 'mali3',
  thesarLeave: [60, 1000],
  oraVerdhe: 'humbur',
  nastradin2: 'nastradin1',
  nastradinUrte: 'nastradin1',
  kostandinPushim: 'kostandin1',
  besaBekim: 'lendina',
  oda1: 'libriDiell',
  odaPlak: 'libriDiell',
  udhetaret: 'libriDiell',
  kengaLahute: 'libriDiell',
  udhetaretBisede: 'libriDiell',
  udhetaretBisede2: 'libriDiell',
  tregMal: 'libriDiell',
  tregDet: 'libriDiell',
  tregMujo: 'libriDiell',
  tregDragua: 'libriDiell',
  oda2: 'libriDiell',
  mujo1: [604, -330],
  mujo2: 'mujo1',
  mujo3: 'mujo1',
  mujo4: 'mujo1',
  mujoFund: 'mujo1',
  ujkuLind1: 'pylliThelle',
  ujkuFund: 'pylliThelle',
  verbti1: [170, -610],
  verbtiFund: 'verbti1',
  verbtiVdes: 'verbti1',
  omer1: [634, -388],
  omer2: 'omer1',
  omerFund: 'omer1',
  lubia1: 'udhaThate',
  lubiaKoke: 'udhaThate',
  lubiaFund: 'udhaThate',
  prende1: 'uji',
  prendeFund: 'uji',
  riddle1: 'ura',
  riddleFund: 'ura',
  // The bird-origin tales heard in the back lanes have their own nearby field
  // and eaves; they do not happen at Gjizar's king-road marker.
  cuckoo1: [755, 225],
  cuckooFund: 'cuckoo1',
  cuckooLule: 'cuckoo1',
  arushe1: 'pylli1',
  arushePeme: 'pylli1',
  arusheNate: 'pylli1',
  arusheFund: 'pylli1',
  dhampir1: [-360, 900],
  dhampirFund: 'dhampir1',
  bleta1: 'gjizar1',
  bletaFund: 'gjizar1',
  merimangaFund: 'gjizar1',
  gjinkallaFund: 'gjizar1',
  dallendyshe1: [805, 215],
  dallendysheFund: 'dallendyshe1',
  dallendysheGjak: 'dallendyshe1',
  kukudh1: 'udha',
  kukudhFund: 'udha',
  udhekryq: [458, 66],
  qiell1: [430, -1300],
  qiellDem1: [120, -1390],
  qiellErera1: [760, -1030],
  qiellErera2: 'qiellErera1',
  qiell2: [440, -1480],
  zojzBekim: 'qiell2',
  diellShenjt: 'qiell2',
  zojzRrufe: [560, -1560],
  qiellPrende: [-260, -1080],
  qiellDiell: [-120, -1230],
  demKeq: 'qiellDem1',
  ereHumbur: 'qiellErera1',
  qiellVerbuar: 'qiellErera1',
  prendeBekim: 'qiellPrende',
  ylberKaprcim: [-370, -1010],
  diellApex: 'qiellDiell',
  henaPaqe: [720, -1290],
  fshatiLumi: [232, 616],
  gruaUji1: 'fshatiLumi', // the water-carrier stopped on the bank — same spot as the river scene
  // The master tells the mill's origin from the riverbank approach. The working
  // floor and the night threshold are distinct parts of the same drawn mill.
  lumiMjeshter: [130, 570],
  fushaMulli: [200, 545], // the fields behind the mill — the miller's world, walked

  // the NEW bridge (Ura e Artës) worksite — the masons' yard at the EAST
  // bridgehead, upstream of the old bridge; the half-built span reaches out
  // over the water from here (gUraArtes draws it)
  uraArtes1: [196, 508],
  uraTjeter1: 'uraArtes1', // the worksite visited as a traveller — the same masons' yard
  uraVellezerit: 'uraArtes1', // talking to Pano and Mihal — the same masons' yard
  uraArtes2: 'uraArtes1',
  uraGropa: 'uraArtes1', // the bride at the pit — the same masons' yard
  uraMurim: 'uraArtes1', // the walling — down in the foundation pit itself
  uraArtesShpetim: 'uraArtes1',
  uraArtesMur: 'uraArtes1',
  // the brothers' HOUSEHOLD (Ura e Artës arc) — one hearth among the homes just
  // up the lane from fshatiJeta: the night besa choice + the morning bride-test
  uraNata: [352, 462],
  uraMengjes: 'uraNata',
  mulli1: [166, 602],
  punaMulli: 'mulli1',
  mulliFund: 'mulli1',
  mulliKeq: 'mulli1',
  xhindMulli: [146, 584],
  xhindMulliFund: 'xhindMulli',
  xhindMulliKeq: 'xhindMulli',
  kroi1: [180, 672],
  kroiFund: 'kroi1',
  // the tanners' bank under the old bridge (Ura e Tabakëve) — its own spot on
  // the water, downstream of the stonebridge glyph
  tabaket1: [220, 662],
  punaTabak: 'tabaket1',
  tabakFund: 'tabaket1',
  kisha1: [378, 176],
  kishaFund: 'kisha1',
  varret1: [298, 132],
  varretFund: 'varret1',
  burrnesha1: 'libriDiell',
  burrneshaFund: 'libriDiell',
  skender1: 'libriDiell',
  skender2: 'libriDiell',
  skenderFund: 'libriDiell',
  skenderKeq: 'libriDiell',
  lahuta1: 'libriDiell',
  lahutaFund: 'libriDiell',
}

// ---- derived (do not edit below) -------------------------------------------
// NODE_POS: resolved [x,y] per node. PLACE_OF: node -> the anchor node whose
// spot it shares (itself for anchors). PLACE_NODES: anchor -> every node
// standing there, anchor first.
export const NODE_POS = {}
export const PLACE_OF = {}
export const PLACE_NODES = {}
for (const id of Object.keys(NODE_AT)) {
  let a = id, hops = 0
  while (typeof NODE_AT[a] === 'string') {
    a = NODE_AT[a]
    if (++hops > 32) throw new Error(`nodePositions: alias cycle through '${id}'`)
  }
  if (!Array.isArray(NODE_AT[a])) throw new Error(`nodePositions: '${id}' stands at unknown node '${a}'`)
  PLACE_OF[id] = a
  NODE_POS[id] = NODE_AT[a]
}
for (const id of Object.keys(NODE_AT)) {
  const a = PLACE_OF[id]
  const l = (PLACE_NODES[a] ||= [a])
  if (id !== a) l.push(id)
}
