// HAND-AUTHORED map placement — one physical spot, ONE coordinate.
// Each entry is either
//   id: [x, y]       the node stands at its OWN spot (most nodes), or
//   id: 'anchorId'   the node stands AT that node's spot — the story
//                    continues at the same physical place.
// Move a place by editing its single [x, y]: everyone standing there moves
// with it. If the character moves even slightly, the node gets its OWN
// coordinate — never reuse another spot's numbers (mapaudit flags collisions).
export const NODE_AT = {
  start: [70, 500],
  lendina: [-430, 452],
  plaka: [576, 388],
  agaYmer1: 'plaka',
  syriKeq1: [404, 496],
  syriKeqFund: 'syriKeq1',
  breshka1: [348, 614],
  breshkaMire: 'breshka1',
  breshkaFund: 'breshka1',
  agaYmer2: 'plaka',
  agaYmerStay: 'plaka',
  agaYmerFund: 'plaka',
  pylli1: [-560, 400],
  pylliThelle: [-700, 480],
  shokuUjk: 'pylliThelle',
  udha: [-560, 720],
  stihi1: [-560, 560],
  stihiDjeg: 'stihi1',
  stihiFund: 'stihi1',
  // ── Jutbina — the kreshnik hamlet on its highland shelf: each tale has its
  // own kulla / spot around the hamlet centre; the zanas' meadow lies above,
  // the mejdan duelling ground below, the lament-house at the west edge.
  vajtim1: [478, -390],
  mujoHak1: [300, -320],
  mujoHakFund: 'mujoHak1',
  mujoHakKeq: 'mujoHak1',
  mejdan1: [470, -260],
  mejdan2: 'mejdan1',
  mejdanKeq: 'mejdan1',
  besaVella: 'mejdan1',
  besaThyer: 'mejdan1',
  vajtimFund: 'vajtim1',
  lumi: [200, 820],
  veraDite1: [458, 484],
  veraDiteFund: 'veraDite1',
  flocka1: [140, 1560],
  flockaFund: 'flocka1',
  deti1: [1010, 800],
  detiThelle1: [1360, 1200],
  detiThelle2: [1680, 1420],
  detiNuse: 'detiThelle2',
  detiStuhi: 'detiThelle1',
  zana1: [300, 960],
  zanaQumesht: [260, 1140],
  zanaKripe: 'zanaQumesht',
  rrethi: [300, 1150],
  mali1: [180, -430],
  cajMali1: 'mali1',
  mali2: [140, -500],
  mali3: [110, -560],
  tomor1: [470, -720],
  tomor2: 'tomor1',
  pusi: [420, 1960],
  bota1: [380, 2070],
  bota2: [200, 2320],
  porta1: [470, 2210],
  portaVdes: 'porta1',
  bukura1: [640, 2120],
  bukura2: 'bukura1',
  kulshedra1: [620, 2340],
  fitorja: 'kulshedra1',
  pusi2: [1560, 1640],
  shqiponja1: 'pusi2',
  siperfaqja: [1180, 1600],
  kala1: [300, 1360],
  kala2: 'kala1',
  shtepia: [360, 480],
  dranguasi: 'kulshedra1',
  mishiVetes: 'pusi2',
  fshehur: [95, 900],
  thesarOra: [120, 950],
  shpellaHyrje: [180, 1290],
  shpellaRruget: [235, 1430],
  qyteti: [300, 2060],
  qytetiUdhetar: 'qyteti',
  qytetiUdhetar2: 'qyteti',
  qytetiUdhetar3: 'qyteti',
  qytetiUdhetar4: 'qyteti',
  // ── the living quarter of the dead city — a real drawn plaza: the square at
  // its heart, the bazaar NE, the inn SE, the healer SW, the traveller by the
  // street in from the gate, the way-signs at the far edge.
  sheshi: [400, 2140],
  lemoshaFund: 'sheshi',
  tregtari: [447, 2122],
  blerjaBuke: 'tregtari',
  blerjaKripe: 'tregtari',
  shitjaCaj: 'tregtari',
  tregtari2: 'tregtari',
  blerjaLahuta: 'tregtari',
  plisiFund: 'tregtari',
  xhubletaFund: 'tregtari',
  bujtina: [434, 2181],
  gjumiBujtina: 'bujtina',
  kafeja1: 'bujtina',
  kafejaFund: 'bujtina',
  fallFund: 'bujtina',
  gezuarFund: 'bujtina',
  sheruesi: [352, 2172],
  sherimiBar: 'sheruesi',
  besimeFund: 'sheruesi',
  udhetariHuaj: [362, 2106],
  kurbetiFund: 'udhetariHuaj',
  udhaShenja: [415, 2216],
  thesar2: [430, 2210],
  thesarKthyer: [500, 2250],
  gjarperVrare: 'thesar2',
  gjarperNgrene: 'thesar2',
  murosur: 'kala1',
  djegur: [710, 2280],
  rene: 'pusi2',
  detiUp: 'detiThelle2',
  detiNgrene: 'detiThelle2',
  humbur: [560, 2340],
  oraBardhe: 'humbur',
  oraZeze: 'humbur',
  eaten: 'pylliThelle',
  pylliLoop: [-440, 540],
  shtojzovalle1: [-460, 800],
  shtojzovalle2: 'shtojzovalle1',
  shtojzovalleVallja: 'shtojzovalle1',
  shtojzovalleLot: 'shtojzovalle1',
  shtojzovalleNuse: 'shtojzovalle1',
  shtojzovalleBekim: 'shtojzovalle1',
  shtrigaNate: [-410, 480],
  besaFire: 'lendina',
  shtrigaIkur: 'shtrigaNate',
  gjumi: [-450, 425],
  fshatiDil: [604, 180],
  dilFrike: 'fshatiDil',
  ura: [380, 1240],
  maja: [300, -820],
  jutbina: [540, -360],
  mujiZana1: [505, -432],
  mujiZana2: 'mujiZana1',
  mujiFund: 'mujiZana1',
  mujiPasuri: 'mujiZana1',
  mujiDije: 'mujiZana1',
  tomor3: 'tomor1',
  dera: 'bota1',
  sprova: [140, 2130],
  gjarpri: 'bota2',
  uji: [180, 2360],
  kthimi: [560, 2080],
  udhaKthimit: [180, 1210],
  ktheu3: [1180, 1980],
  shqipe1: [120, 1320],
  shqipe2: [95, 1250],
  shqipe3: 'shqipe2',
  shqipeFund: 'shqipe2',
  sari1: 'pusi',
  sari2: 'pusi',
  sariFund: 'pusi',
  gjarperBurr1: 'bota2',
  gjarperBurrVdes: 'bota2',
  gjarperBurr2: 'bota2',
  gjarperKerkim: 'bota2',
  gjarperOrigin: 'bota2',
  gjarperRefuz: [110, 2400],
  gjarperKulshedra: [1700, 1750],
  gjarperKulVdes: 'gjarperKulshedra',
  gjarperBurrFund: 'gjarperKulshedra',
  nastradin1: [404, 150],
  nastradinFund: 'nastradin1',
  kostandin1: [336, 256],
  kostandin2: 'kostandin1',
  kostandin3: 'kostandin1',
  kostandinFund: 'kostandin1',
  gjizar1: [672, 214],
  gjizar2: [720, 164],
  gjizarUdha: 'gjizar2',
  gjizarPallat: 'gjizar2',
  gjizarKap: 'gjizar2',
  gjizarTradheti: 'gjizar2',
  gjizarPus: 'gjizar2',
  gjizarFund: 'gjizar2',
  shpirag1: 'maja',
  shpiragFund: 'maja',
  dhia1: [80, -420],
  dhiaFund: 'dhia1',
  tre1: [280, 2470],
  tre2: 'tre1',
  tre3: 'tre1',
  udhetimi1: [300, 2380],
  udhetimi2: [240, 2440],
  bukuraThellesi: 'bukura1',
  bregu: [780, 1080],
  balozMotra: [720, 1040],
  balozTribut: 'balozMotra',
  balozZgjedh: 'balozMotra',
  balozLufte: [880, 1130],
  balozKoke: [960, 1200],
  balozFitore: [640, 1100],
  bregFle: 'bregu',
  bregHumb: [1000, 1080],
  zanaProva: [410, 1040],
  zanaProva2: 'zanaProva',
  zanaGold: 'zanaQumesht',
  zanaDije: 'zanaQumesht',
  zanaFole: [80, 1000],
  foleShpetuar: 'zanaFole',
  tomorProva: 'tomor1',
  tomorStuhi: 'tomor1',
  ngjitja1: 'pusi2',
  ngjitja2: 'pusi2',
  ngjitja3: 'pusi2',
  fshatiSheshi: [499, 432],
  sheshiKisha: [498, 380], // the church side of the square, by the mosque and church road
  pazari1: [505, 575], // the pazar stalls on the market street south of the square
  dasma1: 'sheshiKisha',
  dasmaFund: 'sheshiKisha',
  valleFund: 'sheshiKisha',
  sheshiPlak: 'fshatiSheshi',
  sheshiPlak2: 'fshatiSheshi',
  sheshiPlak3: 'fshatiSheshi',
  pusiThate: [480, 444],
  peri1: [180, -520],
  periFund: 'peri1',
  periKeq: 'peri1',
  xhind1: 'pusiThate',
  xhindFund: 'pusiThate',
  xhindKeq: 'pusiThate',
  nenaDiell1: [516, 400],
  nenaDiellFund: 'nenaDiell1',
  karkanxholl1: [-720, 820],
  karkanxhollFund: 'karkanxholl1',
  karkanxhollKeq: 'karkanxholl1',
  dhelpra1: [-360, 600],
  dhelpra2: 'dhelpra1',
  dhelpraFund: 'dhelpra1',
  dhelpraKeq: 'dhelpra1',
  nastradinGjyq1: 'nastradin1',
  nastradinGjyqFund: 'nastradin1',
  nastradinGjyqKeq: 'nastradin1',
  rusha1: [610, -428],
  rushaFund: 'rusha1',
  rushaKeq: 'rusha1',
  halil1: [566, -392],
  halilFund: 'halil1',
  halilKeq: 'halil1',
  arushe2: 'pylli1',
  pallatiZi: [768, 448],
  pallatRoje: 'pallatiZi',
  pallatRojeZi: 'pallatiZi',
  pallatRojePse: 'pallatiZi',
  libriDiell: [418, 392],
  pallatiKthim: 'pallatiZi',
  // ── the Sun's house — a real explorable compound on its cloud-plateau:
  // house → garden (west wing) → golden oda (east wing) → the forecourt where
  // the beasts are summoned (south gate) → the road of the Sun down the ray,
  // with the sun-tree beside it (the escape, rrugaDielli2, ends by the village).
  diellShtepi1: [300, -1150],
  diellKopsht: [205, -1085],
  diellKopshtFol: 'diellKopsht',
  diellOda: [385, -1125],
  diellThirrKul: [300, -1062],
  diellKulVdes: 'diellThirrKul',
  rrugaDielli1: [300, -985],
  pemaDielli: [382, -935],
  pemaVdes: 'pemaDielli',
  rrugaDielli2: [400, 120],
  kopshtMermer1: [690, 470],
  kopshtMermer2: 'kopshtMermer1',
  mermerZgjim: 'kopshtMermer1',
  mermerTradheti: 'kopshtMermer1',
  patatGruaja: 'kopshtMermer1',
  mbretiDrejtesi: 'kopshtMermer1',
  patatHesht: 'kopshtMermer1',
  mermerSli: 'kopshtMermer1',
  fshatiLanes: [878, 468],
  djepi1: [884, 542],
  djepi3: 'djepi1',
  djepiKeq: 'djepi1',
  djepi2: 'djepi1',
  djepiFund: 'djepi1',
  fshatiJeta: [322, 430],
  jetaBaba: 'fshatiJeta',
  jetaBaba2: 'fshatiJeta',
  jetaGrua: 'fshatiJeta',
  jetaGrua2: 'fshatiJeta',
  vatra: [300, 378],
  qilim: [288, 468],
  bariu: [300, 560],
  punaBariu: 'bariu',
  gjysmegjel1: [392, 566],
  gjysmegjel2: 'gjysmegjel1',
  gjysmegjelFund: 'gjysmegjel1',
  kulle1: [868, 392],
  kulle2: 'kulle1',
  kulleFal: 'kulle1',
  kulleGjak: 'kulle1',
  fshatiBesa: [430, 236],
  fshatiCaul: 'fshatiBesa',
  udheNate: 'udha',
  udheLugat: 'udha',
  udheOra: 'udha',
  kalaVllezer: 'kala1',
  kalaBesa: 'kala1',
  kalaRozafa: 'kala1',
  kulshLufte1: 'kulshedra1',
  bijaHene1: [500, 2400],
  bijaHeneFund: [500, 2470],
  kulshLufte2: 'kulshedra1',
  springReturn: [670, 2260],
  bukuraKthim: [710, 2200],
  udhaThate: [-460, 640],
  maliHumbur: [500, -975],
  lumiHumbur: [230, 1075],
  botaHumbur: [360, 1890],
  ujkuUje: 'udhaThate',
  udhaSyri: [-320, 720],
  syriFund: 'udhaSyri',
  uraFshaj: [310, 1120],
  maliStuhi: 'mali3',
  zbritjaThelle: [400, 2020],
  qeniGate: 'bota1',
  majaEagle: 'tomor1',
  tomorBekim: 'tomor1',
  tomorZbritje: [360, -160],
  ujiShpella: [330, 2290],
  ktheu1: [1120, 1680],
  ktheu2: [1220, 1830],
  nenaShtrige: 'ktheu2',
  bukuraLirim: 'bukura1',
  kalaBuna: [300, 1200],
  kalaGji: 'kala1',
  dordolec1: [554, 480],
  dordolec2: 'dordolec1',
  dordolecSyriFund: 'dordolec1',
  dordolecFund: [540, 430],
  bolla1: [330, 850],
  bolla2: 'bolla1',
  bollaFund: 'bolla1',
  katallan1: [-40, -360],
  katallanRob: 'katallan1',
  katallanGur: 'katallan1',
  katallanZjarr: 'katallan1',
  katallanVerbim: 'katallan1',
  katallanFund: 'katallan1',
  katallanVdes: 'katallan1',
  gjak1: 'fshatiDil',
  gjak2: 'fshatiDil',
  gjakFund: 'fshatiDil',
  zuku1: [668, -318],
  zuku2: 'zuku1',
  zukuFund: 'zuku1',
  // the sword-brothers tale marches west from the bear glade toward the palace:
  // the brothers -> the moat leap -> the road to the palace gate
  kordha1: [-600, 352],
  kordha2: [-680, 260],
  kordhaMoat: [-648, 306],
  kordhaMoatVdes: 'kordhaMoat',
  kordhaUdha: [-668, 282],
  kordhaPallat: 'kordha2',
  kordhaZjarr: 'kordha2',
  kordhaProva: 'kordha2',
  kordhaProvaVdes: 'kordha2',
  kordhaFund: 'kordha2',
  kordhaDeti: 'kordha2',
  shurdhi1: [60, -680],
  shurdhiFund: 'shurdhi1',
  kali1: 'mali3',
  kaliFund: 'mali3',
  thesarLeave: [60, 1000],
  oraVerdhe: 'humbur',
  nastradin2: 'nastradin1',
  nastradinUrte: 'nastradin1',
  kostandinPushim: 'kostandin1',
  besaBekim: 'lendina',
  oda1: 'libriDiell',
  odaPlak: 'libriDiell',
  udhetaret: 'libriDiell',
  kengaLahute: 'libriDiell',
  udhetaretBisede: 'libriDiell',
  udhetaretBisede2: 'libriDiell',
  tregMal: 'libriDiell',
  tregDet: 'libriDiell',
  tregMujo: 'libriDiell',
  tregDragua: 'libriDiell',
  oda2: 'libriDiell',
  mujo1: [604, -330],
  mujo2: 'mujo1',
  mujo3: 'mujo1',
  mujo4: 'mujo1',
  mujoFund: 'mujo1',
  ujkuLind1: 'pylliThelle',
  ujkuFund: 'pylliThelle',
  verbti1: [170, -610],
  verbtiFund: 'verbti1',
  verbtiVdes: 'verbti1',
  omer1: [634, -388],
  omer2: 'omer1',
  omerFund: 'omer1',
  lubia1: 'udhaThate',
  lubiaKoke: 'udhaThate',
  lubiaFund: 'udhaThate',
  prende1: 'uji',
  prendeFund: 'uji',
  riddle1: 'ura',
  riddleFund: 'ura',
  cuckoo1: 'gjizar2',
  cuckooFund: 'gjizar2',
  arushe1: 'pylli1',
  arushePeme: 'pylli1',
  arusheNate: 'pylli1',
  arusheFund: 'pylli1',
  dhampir1: [-360, 900],
  dhampirFund: 'dhampir1',
  bleta1: 'gjizar1',
  bletaFund: 'gjizar1',
  merimangaFund: 'gjizar1',
  dallendyshe1: 'gjizar2',
  dallendysheFund: 'gjizar2',
  kukudh1: 'udha',
  kukudhFund: 'udha',
  udhekryq: [458, 66],
  qiell1: [430, -1300],
  qiellDem1: [120, -1390],
  qiellErera1: [760, -1030],
  qiellErera2: 'qiellErera1',
  qiell2: [440, -1420],
  zojzBekim: 'qiell2',
  diellShenjt: 'qiell2',
  zojzRrufe: [560, -1450],
  qiellPrende: [-260, -1080],
  qiellDiell: [-120, -1230],
  demKeq: 'qiellDem1',
  ereHumbur: 'qiellErera1',
  qiellVerbuar: 'qiellErera1',
  prendeBekim: 'qiellPrende',
  ylberKaprcim: [-370, -1010],
  diellApex: 'qiellDiell',
  henaPaqe: [720, -1290],
  fshatiLumi: [232, 616],
  gruaUji1: 'fshatiLumi', // the water-carrier stopped on the bank — same spot as the river scene
  lumiMjeshter: [166, 602],
  lumiMjeshter2: 'lumiMjeshter',
  uraArtes1: [132, 500],
  uraArtes2: 'uraArtes1',
  uraArtesShpetim: 'uraArtes1',
  uraArtesMur: 'uraArtes1',
  mulli1: 'lumiMjeshter',
  punaMulli: 'lumiMjeshter',
  mulliFund: 'lumiMjeshter',
  mulliKeq: 'lumiMjeshter',
  kroi1: [178, 674],
  kroiFund: 'kroi1',
  // the tanners' bank under the old bridge (Ura e Tabakëve) — its own spot on
  // the water, downstream of the stonebridge glyph
  tabaket1: [220, 662],
  punaTabak: 'tabaket1',
  tabakFund: 'tabaket1',
  kisha1: [378, 176],
  kishaFund: 'kisha1',
  varret1: [298, 132],
  varretFund: 'varret1',
  burrnesha1: 'libriDiell',
  burrneshaFund: 'libriDiell',
  skender1: 'libriDiell',
  skender2: 'libriDiell',
  skenderFund: 'libriDiell',
  lahuta1: 'libriDiell',
  lahutaFund: 'libriDiell',
}

// ---- derived (do not edit below) -------------------------------------------
// NODE_POS: resolved [x,y] per node. PLACE_OF: node -> the anchor node whose
// spot it shares (itself for anchors). PLACE_NODES: anchor -> every node
// standing there, anchor first.
export const NODE_POS = {}
export const PLACE_OF = {}
export const PLACE_NODES = {}
for (const id of Object.keys(NODE_AT)) {
  let a = id, hops = 0
  while (typeof NODE_AT[a] === 'string') {
    a = NODE_AT[a]
    if (++hops > 32) throw new Error(`nodePositions: alias cycle through '${id}'`)
  }
  if (!Array.isArray(NODE_AT[a])) throw new Error(`nodePositions: '${id}' stands at unknown node '${a}'`)
  PLACE_OF[id] = a
  NODE_POS[id] = NODE_AT[a]
}
for (const id of Object.keys(NODE_AT)) {
  const a = PLACE_OF[id]
  const l = (PLACE_NODES[a] ||= [a])
  if (id !== a) l.push(id)
}
